/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "teseocallbacks.h"
#include "teseointerface.h"
#include "teseosupport.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_win_neuronteseo (void)
{
  GtkWidget *win_neuronteseo;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separator2;
  GtkWidget *preferences_2;
  GtkWidget *image103;
  GtkWidget *separator4;
  GtkWidget *import1;
  GtkWidget *image104;
  GtkWidget *import1_menu;
  GtkWidget *path2;
  GtkWidget *dxf2;
  GtkWidget *trace2;
  GtkWidget *sac2;
  GtkWidget *sac_xy2;
  GtkWidget *sisma2;
  GtkWidget *timemark2;
  GtkWidget *export1;
  GtkWidget *image105;
  GtkWidget *export1_menu;
  GtkWidget *path1;
  GtkWidget *dxf1;
  GtkWidget *trace1;
  GtkWidget *sac1;
  GtkWidget *sac_xy1;
  GtkWidget *sisma1;
  GtkWidget *timemark1;
  GtkWidget *separator5;
  GtkWidget *examples2;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *path3;
  GtkWidget *path3_menu;
  GtkWidget *resample1;
  GtkWidget *align_all1;
  GtkWidget *link_all1;
  GtkWidget *move_and_rotation1;
  GtkWidget *fitting_polyline1;
  GtkWidget *fitting_bezier1;
  GtkWidget *recover_last2;
  GtkWidget *separator3;
  GtkWidget *timemark3;
  GtkWidget *timemark3_menu;
  GtkWidget *evaluate_middle_tms1;
  GtkWidget *adjustment1;
  GtkWidget *neural_network1;
  GtkWidget *neural_network1_menu;
  GtkWidget *info_window_1;
  GtkWidget *image106;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *help1;
  GtkWidget *image107;
  GtkWidget *about1;
  GtkWidget *image108;
  GtkWidget *handlebox2;
  GtkWidget *alignment1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *button10;
  GtkWidget *separatortoolitem1;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton10;
  GtkWidget *radiobutton9;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton17;
  GtkWidget *radiobutton18;
  GtkWidget *separatortoolitem2;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *handlebox3;
  GtkWidget *toolbar2;
  GtkWidget *button12;
  GtkWidget *button13;
  GtkWidget *button14;
  GtkWidget *button15;
  GtkWidget *hbox10;
  GtkWidget *notebook2;
  GtkWidget *frame13;
  GtkWidget *vbox23;
  GtkWidget *frame18;
  GtkWidget *table4;
  GtkWidget *label74;
  GtkObject *spinbutton18_adj;
  GtkWidget *spinbutton18;
  GtkObject *spinbutton19_adj;
  GtkWidget *spinbutton19;
  GtkWidget *label73;
  GtkWidget *label72;
  GtkWidget *frame22;
  GtkWidget *label88;
  GtkWidget *label86;
  GtkWidget *frame23;
  GtkWidget *label89;
  GtkWidget *label87;
  GtkWidget *label55;
  GtkWidget *label48;
  GtkWidget *frame19;
  GtkWidget *vbox24;
  GtkWidget *table5;
  GtkWidget *frame20;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *vbox25;
  GtkWidget *label78;
  GtkObject *spinbutton20_adj;
  GtkWidget *spinbutton20;
  GtkWidget *vbox27;
  GtkWidget *label79;
  GtkObject *spinbutton21_adj;
  GtkWidget *spinbutton21;
  GtkWidget *table6;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkObject *spinbutton22_adj;
  GtkWidget *spinbutton22;
  GtkObject *spinbutton23_adj;
  GtkWidget *spinbutton23;
  GtkObject *spinbutton24_adj;
  GtkWidget *spinbutton24;
  GtkWidget *label80;
  GtkWidget *label75;
  GtkWidget *frame14;
  GtkWidget *vbox17;
  GtkWidget *table3;
  GtkWidget *frame16;
  GtkWidget *label66;
  GtkWidget *label65;
  GtkWidget *vbox18;
  GtkWidget *label64;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkWidget *vbox20;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *radiobutton12;
  GtkWidget *vbox19;
  GtkWidget *label63;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *label57;
  GtkWidget *label49;
  GtkWidget *frame15;
  GtkWidget *vbox21;
  GtkWidget *frame21;
  GtkWidget *vbox28;
  GtkWidget *hbox13;
  GtkWidget *label90;
  GtkWidget *button11;
  GtkWidget *image109;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview1;
  GtkWidget *label84;
  GtkWidget *frame17;
  GtkWidget *hbox11;
  GtkWidget *checkbutton13;
  GtkWidget *vbox22;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton15;
  GtkWidget *hbox12;
  GtkWidget *label70;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkWidget *label71;
  GtkWidget *label59;
  GtkWidget *label54;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  win_neuronteseo = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_neuronteseo, "win_neuronteseo");
  gtk_window_set_title (GTK_WINDOW (win_neuronteseo), "Teseo 2.0");
  gtk_window_set_position (GTK_WINDOW (win_neuronteseo), GTK_WIN_POS_MOUSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (win_neuronteseo), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Session");
  gtk_widget_set_name (menuitem4, "menuitem4");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem4_menu, "menuitem4_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_set_name (new1, "new1");
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_set_name (open1, "open1");
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_set_name (save1, "save1");
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_set_name (save_as1, "save_as1");
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), save_as1);

  separator2 = gtk_menu_item_new ();
  gtk_widget_set_name (separator2, "separator2");
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  preferences_2 = gtk_image_menu_item_new_with_mnemonic ("_Preferences ...");
  gtk_widget_set_name (preferences_2, "preferences_2");
  gtk_widget_show (preferences_2);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), preferences_2);
  GTK_WIDGET_SET_FLAGS (preferences_2, GTK_CAN_FOCUS);
  gtk_widget_add_accelerator (preferences_2, "activate", accel_group,
                              GDK_P, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image103 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image103, "image103");
  gtk_widget_show (image103);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (preferences_2), image103);

  separator4 = gtk_menu_item_new ();
  gtk_widget_set_name (separator4, "separator4");
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  import1 = gtk_image_menu_item_new_with_mnemonic ("_Import ...");
  gtk_widget_set_name (import1, "import1");
  gtk_widget_show (import1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), import1);

  image104 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image104, "image104");
  gtk_widget_show (image104);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (import1), image104);

  import1_menu = gtk_menu_new ();
  gtk_widget_set_name (import1_menu, "import1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (import1), import1_menu);

  path2 = gtk_menu_item_new_with_mnemonic ("_Path");
  gtk_widget_set_name (path2, "path2");
  gtk_widget_show (path2);
  gtk_container_add (GTK_CONTAINER (import1_menu), path2);

  dxf2 = gtk_menu_item_new_with_mnemonic ("_DXF");
  gtk_widget_set_name (dxf2, "dxf2");
  gtk_widget_show (dxf2);
  gtk_container_add (GTK_CONTAINER (import1_menu), dxf2);

  trace2 = gtk_menu_item_new_with_mnemonic ("_Trace");
  gtk_widget_set_name (trace2, "trace2");
  gtk_widget_show (trace2);
  gtk_container_add (GTK_CONTAINER (import1_menu), trace2);

  sac2 = gtk_menu_item_new_with_mnemonic ("_SAC");
  gtk_widget_set_name (sac2, "sac2");
  gtk_widget_show (sac2);
  gtk_container_add (GTK_CONTAINER (import1_menu), sac2);

  sac_xy2 = gtk_menu_item_new_with_mnemonic ("SA_C XY");
  gtk_widget_set_name (sac_xy2, "sac_xy2");
  gtk_widget_show (sac_xy2);
  gtk_container_add (GTK_CONTAINER (import1_menu), sac_xy2);

  sisma2 = gtk_menu_item_new_with_mnemonic ("S_ISMA");
  gtk_widget_set_name (sisma2, "sisma2");
  gtk_widget_show (sisma2);
  gtk_container_add (GTK_CONTAINER (import1_menu), sisma2);

  timemark2 = gtk_menu_item_new_with_mnemonic ("_Timemark");
  gtk_widget_set_name (timemark2, "timemark2");
  gtk_widget_show (timemark2);
  gtk_container_add (GTK_CONTAINER (import1_menu), timemark2);

  export1 = gtk_image_menu_item_new_with_mnemonic ("_Export ...");
  gtk_widget_set_name (export1, "export1");
  gtk_widget_show (export1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), export1);

  image105 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image105, "image105");
  gtk_widget_show (image105);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (export1), image105);

  export1_menu = gtk_menu_new ();
  gtk_widget_set_name (export1_menu, "export1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (export1), export1_menu);

  path1 = gtk_menu_item_new_with_mnemonic ("_Path");
  gtk_widget_set_name (path1, "path1");
  gtk_widget_show (path1);
  gtk_container_add (GTK_CONTAINER (export1_menu), path1);

  dxf1 = gtk_menu_item_new_with_mnemonic ("_DXF");
  gtk_widget_set_name (dxf1, "dxf1");
  gtk_widget_show (dxf1);
  gtk_container_add (GTK_CONTAINER (export1_menu), dxf1);

  trace1 = gtk_menu_item_new_with_mnemonic ("_Trace");
  gtk_widget_set_name (trace1, "trace1");
  gtk_widget_show (trace1);
  gtk_container_add (GTK_CONTAINER (export1_menu), trace1);

  sac1 = gtk_menu_item_new_with_mnemonic ("_SAC");
  gtk_widget_set_name (sac1, "sac1");
  gtk_widget_show (sac1);
  gtk_container_add (GTK_CONTAINER (export1_menu), sac1);

  sac_xy1 = gtk_menu_item_new_with_mnemonic ("SA_C XY");
  gtk_widget_set_name (sac_xy1, "sac_xy1");
  gtk_widget_show (sac_xy1);
  gtk_container_add (GTK_CONTAINER (export1_menu), sac_xy1);

  sisma1 = gtk_menu_item_new_with_mnemonic ("S_ISMA");
  gtk_widget_set_name (sisma1, "sisma1");
  gtk_widget_show (sisma1);
  gtk_container_add (GTK_CONTAINER (export1_menu), sisma1);

  timemark1 = gtk_menu_item_new_with_mnemonic ("_Timemark");
  gtk_widget_set_name (timemark1, "timemark1");
  gtk_widget_show (timemark1);
  gtk_container_add (GTK_CONTAINER (export1_menu), timemark1);

  separator5 = gtk_menu_item_new ();
  gtk_widget_set_name (separator5, "separator5");
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (export1_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  examples2 = gtk_menu_item_new_with_mnemonic ("_Examples");
  gtk_widget_set_name (examples2, "examples2");
  gtk_widget_show (examples2);
  gtk_container_add (GTK_CONTAINER (export1_menu), examples2);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quit1, "quit1");
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  path3 = gtk_menu_item_new_with_mnemonic ("_Path");
  gtk_widget_set_name (path3, "path3");
  gtk_widget_show (path3);
  gtk_container_add (GTK_CONTAINER (menubar1), path3);

  path3_menu = gtk_menu_new ();
  gtk_widget_set_name (path3_menu, "path3_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (path3), path3_menu);

  resample1 = gtk_menu_item_new_with_mnemonic ("R_esample");
  gtk_widget_set_name (resample1, "resample1");
  gtk_widget_show (resample1);
  gtk_container_add (GTK_CONTAINER (path3_menu), resample1);

  align_all1 = gtk_menu_item_new_with_mnemonic ("_Align All");
  gtk_widget_set_name (align_all1, "align_all1");
  gtk_widget_show (align_all1);
  gtk_container_add (GTK_CONTAINER (path3_menu), align_all1);

  link_all1 = gtk_menu_item_new_with_mnemonic ("_Link All");
  gtk_widget_set_name (link_all1, "link_all1");
  gtk_widget_show (link_all1);
  gtk_container_add (GTK_CONTAINER (path3_menu), link_all1);

  move_and_rotation1 = gtk_menu_item_new_with_mnemonic ("_Move and Rotation");
  gtk_widget_set_name (move_and_rotation1, "move_and_rotation1");
  gtk_widget_show (move_and_rotation1);
  gtk_container_add (GTK_CONTAINER (path3_menu), move_and_rotation1);

  fitting_polyline1 = gtk_menu_item_new_with_mnemonic ("Fitting _Polyline");
  gtk_widget_set_name (fitting_polyline1, "fitting_polyline1");
  gtk_widget_show (fitting_polyline1);
  gtk_container_add (GTK_CONTAINER (path3_menu), fitting_polyline1);

  fitting_bezier1 = gtk_menu_item_new_with_mnemonic ("Fitting _Bezier");
  gtk_widget_set_name (fitting_bezier1, "fitting_bezier1");
  gtk_widget_show (fitting_bezier1);
  gtk_container_add (GTK_CONTAINER (path3_menu), fitting_bezier1);

  recover_last2 = gtk_menu_item_new_with_mnemonic ("_Recover last");
  gtk_widget_set_name (recover_last2, "recover_last2");
  gtk_widget_show (recover_last2);
  gtk_container_add (GTK_CONTAINER (path3_menu), recover_last2);

  separator3 = gtk_menu_item_new ();
  gtk_widget_set_name (separator3, "separator3");
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (path3_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  timemark3 = gtk_menu_item_new_with_mnemonic ("_Timemark");
  gtk_widget_set_name (timemark3, "timemark3");
  gtk_widget_show (timemark3);
  gtk_container_add (GTK_CONTAINER (path3_menu), timemark3);

  timemark3_menu = gtk_menu_new ();
  gtk_widget_set_name (timemark3_menu, "timemark3_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (timemark3), timemark3_menu);

  evaluate_middle_tms1 = gtk_menu_item_new_with_mnemonic ("_Evaluate middle TMs");
  gtk_widget_set_name (evaluate_middle_tms1, "evaluate_middle_tms1");
  gtk_widget_show (evaluate_middle_tms1);
  gtk_container_add (GTK_CONTAINER (timemark3_menu), evaluate_middle_tms1);

  adjustment1 = gtk_menu_item_new_with_mnemonic ("_Adjustment");
  gtk_widget_set_name (adjustment1, "adjustment1");
  gtk_widget_show (adjustment1);
  gtk_container_add (GTK_CONTAINER (timemark3_menu), adjustment1);

  neural_network1 = gtk_menu_item_new_with_mnemonic ("_Neural Network");
  gtk_widget_set_name (neural_network1, "neural_network1");
  gtk_widget_show (neural_network1);
  gtk_container_add (GTK_CONTAINER (menubar1), neural_network1);

  neural_network1_menu = gtk_menu_new ();
  gtk_widget_set_name (neural_network1_menu, "neural_network1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (neural_network1), neural_network1_menu);

  info_window_1 = gtk_image_menu_item_new_with_mnemonic ("Info Window ...");
  gtk_widget_set_name (info_window_1, "info_window_1");
  gtk_widget_show (info_window_1);
  gtk_container_add (GTK_CONTAINER (neural_network1_menu), info_window_1);

  image106 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image106, "image106");
  gtk_widget_show (image106);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (info_window_1), image106);

  menuitem7 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_set_name (menuitem7, "menuitem7");
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem7_menu, "menuitem7_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  help1 = gtk_image_menu_item_new_with_mnemonic ("_Help ...");
  gtk_widget_set_name (help1, "help1");
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), help1);

  image107 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image107, "image107");
  gtk_widget_show (image107);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (help1), image107);

  about1 = gtk_image_menu_item_new_with_mnemonic ("_About ...");
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about1);

  image108 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image108, "image108");
  gtk_widget_show (image108);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image108);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox2, "handlebox2");
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (handlebox2), alignment1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (alignment1), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-properties", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button10 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button10");
  gtk_widget_set_name (button10, "button10");
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (toolbar1), button10);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem1, "separatortoolitem1");
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  radiobutton10 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton10), "radiobutton10");
  tmp_image = gtk_image_new_from_stock ("gtk-redo", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton10), tmp_image);
  gtk_widget_set_name (radiobutton10, "radiobutton10");
  gtk_widget_show (radiobutton10);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton10);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton10));

  radiobutton9 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton9), "radiobutton9");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton9), tmp_image);
  gtk_widget_set_name (radiobutton9, "radiobutton9");
  gtk_widget_show (radiobutton9);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton9);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton9), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton9));
  gtk_toggle_tool_button_set_active (GTK_TOGGLE_TOOL_BUTTON (radiobutton9), TRUE);

  radiobutton8 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton8), "NN 1");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton8), tmp_image);
  gtk_widget_set_name (radiobutton8, "radiobutton8");
  gtk_widget_show (radiobutton8);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton8);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton8), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton8));

  radiobutton17 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton17), "NN 2");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton17), tmp_image);
  gtk_widget_set_name (radiobutton17, "radiobutton17");
  gtk_widget_show (radiobutton17);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton17);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton17), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton17));

  radiobutton18 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton18), "NN 3");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton18), tmp_image);
  gtk_widget_set_name (radiobutton18, "radiobutton18");
  gtk_widget_show (radiobutton18);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton18);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton18), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton18));

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem2, "separatortoolitem2");
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  tmp_image = gtk_image_new_from_stock ("gtk-go-back", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button7 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button7");
  gtk_widget_set_name (button7, "button7");
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (toolbar1), button7);

  tmp_image = gtk_image_new_from_stock ("gtk-go-forward", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button8 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button8");
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (toolbar1), button8);

  handlebox3 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox3, "handlebox3");
  gtk_widget_show (handlebox3);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox3, TRUE, TRUE, 0);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar2, "toolbar2");
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (handlebox3), toolbar2);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button12 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button12");
  gtk_widget_set_name (button12, "button12");
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (toolbar2), button12);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button13 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button13");
  gtk_widget_set_name (button13, "button13");
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (toolbar2), button13);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button14 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button14");
  gtk_widget_set_name (button14, "button14");
  gtk_widget_show (button14);
  gtk_container_add (GTK_CONTAINER (toolbar2), button14);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button15 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button15");
  gtk_widget_set_name (button15, "button15");
  gtk_widget_show (button15);
  gtk_container_add (GTK_CONTAINER (toolbar2), button15);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox10, TRUE, TRUE, 0);

  notebook2 = gtk_notebook_new ();
  gtk_widget_set_name (notebook2, "notebook2");
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (hbox10), notebook2, TRUE, TRUE, 0);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook2), GTK_POS_BOTTOM);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame13, "frame13");
  gtk_widget_show (frame13);
  gtk_container_add (GTK_CONTAINER (notebook2), frame13);

  vbox23 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox23, "vbox23");
  gtk_widget_show (vbox23);
  gtk_container_add (GTK_CONTAINER (frame13), vbox23);
  gtk_container_set_border_width (GTK_CONTAINER (vbox23), 4);

  frame18 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame18, "frame18");
  gtk_widget_show (frame18);
  gtk_box_pack_start (GTK_BOX (vbox23), frame18, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame18), 0, 0.25);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame18), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 4);

  label74 = gtk_label_new ("Back");
  gtk_widget_set_name (label74, "label74");
  gtk_widget_show (label74);
  gtk_table_attach (GTK_TABLE (table4), label74, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label74), 0, 0.5);

  spinbutton18_adj = gtk_adjustment_new (50, 0, 100, 1, 10, 10);
  spinbutton18 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton18_adj), 1, 0);
  gtk_widget_set_name (spinbutton18, "spinbutton18");
  gtk_widget_show (spinbutton18);
  gtk_table_attach (GTK_TABLE (table4), spinbutton18, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton19_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  spinbutton19 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton19_adj), 1, 0);
  gtk_widget_set_name (spinbutton19, "spinbutton19");
  gtk_widget_show (spinbutton19);
  gtk_table_attach (GTK_TABLE (table4), spinbutton19, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label73 = gtk_label_new ("Forward");
  gtk_widget_set_name (label73, "label73");
  gtk_widget_show (label73);
  gtk_table_attach (GTK_TABLE (table4), label73, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label73), 0, 0.5);

  label72 = gtk_label_new ("Execution Steps");
  gtk_widget_set_name (label72, "label72");
  gtk_widget_show (label72);
  gtk_frame_set_label_widget (GTK_FRAME (frame18), label72);

  frame22 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame22, "frame22");
  gtk_widget_show (frame22);
  gtk_box_pack_start (GTK_BOX (vbox23), frame22, TRUE, TRUE, 0);

  label88 = gtk_label_new ("label88");
  gtk_widget_set_name (label88, "label88");
  gtk_widget_show (label88);
  gtk_container_add (GTK_CONTAINER (frame22), label88);

  label86 = gtk_label_new ("label86");
  gtk_widget_set_name (label86, "label86");
  gtk_widget_show (label86);
  gtk_frame_set_label_widget (GTK_FRAME (frame22), label86);

  frame23 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame23, "frame23");
  gtk_widget_show (frame23);
  gtk_box_pack_start (GTK_BOX (vbox23), frame23, TRUE, TRUE, 0);

  label89 = gtk_label_new ("label89");
  gtk_widget_set_name (label89, "label89");
  gtk_widget_show (label89);
  gtk_container_add (GTK_CONTAINER (frame23), label89);

  label87 = gtk_label_new ("label87");
  gtk_widget_set_name (label87, "label87");
  gtk_widget_show (label87);
  gtk_frame_set_label_widget (GTK_FRAME (frame23), label87);

  label55 = gtk_label_new ("General");
  gtk_widget_set_name (label55, "label55");
  gtk_widget_show (label55);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label55);

  label48 = gtk_label_new ("General");
  gtk_widget_set_name (label48, "label48");
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label48);

  frame19 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame19, "frame19");
  gtk_widget_show (frame19);
  gtk_container_add (GTK_CONTAINER (notebook2), frame19);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox24, "vbox24");
  gtk_widget_show (vbox24);
  gtk_container_add (GTK_CONTAINER (frame19), vbox24);
  gtk_container_set_border_width (GTK_CONTAINER (vbox24), 4);

  table5 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table5, "table5");
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (vbox24), table5, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 7);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 9);

  frame20 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame20, "frame20");
  gtk_widget_show (frame20);
  gtk_table_attach (GTK_TABLE (table5), frame20, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (frame20, 80, 90);

  label76 = gtk_label_new ("");
  gtk_widget_set_name (label76, "label76");
  gtk_widget_show (label76);
  gtk_container_add (GTK_CONTAINER (frame20), label76);

  label77 = gtk_label_new ("Rectangle");
  gtk_widget_set_name (label77, "label77");
  gtk_widget_show (label77);
  gtk_frame_set_label_widget (GTK_FRAME (frame20), label77);

  vbox25 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox25, "vbox25");
  gtk_widget_show (vbox25);
  gtk_table_attach (GTK_TABLE (table5), vbox25, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label78 = gtk_label_new ("Height");
  gtk_widget_set_name (label78, "label78");
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (vbox25), label78, FALSE, FALSE, 0);

  spinbutton20_adj = gtk_adjustment_new (50, 0, 100, 1, 10, 10);
  spinbutton20 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton20_adj), 1, 0);
  gtk_widget_set_name (spinbutton20, "spinbutton20");
  gtk_widget_show (spinbutton20);
  gtk_box_pack_start (GTK_BOX (vbox25), spinbutton20, FALSE, FALSE, 0);

  vbox27 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox27, "vbox27");
  gtk_widget_show (vbox27);
  gtk_table_attach (GTK_TABLE (table5), vbox27, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label79 = gtk_label_new ("Width");
  gtk_widget_set_name (label79, "label79");
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (vbox27), label79, FALSE, FALSE, 0);

  spinbutton21_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  spinbutton21 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton21_adj), 1, 0);
  gtk_widget_set_name (spinbutton21, "spinbutton21");
  gtk_widget_show (spinbutton21);
  gtk_box_pack_start (GTK_BOX (vbox27), spinbutton21, FALSE, FALSE, 0);

  table6 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table6, "table6");
  gtk_widget_show (table6);
  gtk_table_attach (GTK_TABLE (table5), table6, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 12);

  label81 = gtk_label_new ("Low Color");
  gtk_widget_set_name (label81, "label81");
  gtk_widget_show (label81);
  gtk_table_attach (GTK_TABLE (table6), label81, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label81), 0, 0.5);

  label82 = gtk_label_new ("Trace Color");
  gtk_widget_set_name (label82, "label82");
  gtk_widget_show (label82);
  gtk_table_attach (GTK_TABLE (table6), label82, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label82), 0, 0.5);

  label83 = gtk_label_new ("High Color");
  gtk_widget_set_name (label83, "label83");
  gtk_widget_show (label83);
  gtk_table_attach (GTK_TABLE (table6), label83, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label83), 0, 0.5);

  spinbutton22_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton22 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton22_adj), 1, 0);
  gtk_widget_set_name (spinbutton22, "spinbutton22");
  gtk_widget_show (spinbutton22);
  gtk_table_attach (GTK_TABLE (table6), spinbutton22, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton23_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton23 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton23_adj), 1, 0);
  gtk_widget_set_name (spinbutton23, "spinbutton23");
  gtk_widget_show (spinbutton23);
  gtk_table_attach (GTK_TABLE (table6), spinbutton23, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton24_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton24 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton24_adj), 1, 0);
  gtk_widget_set_name (spinbutton24, "spinbutton24");
  gtk_widget_show (spinbutton24);
  gtk_table_attach (GTK_TABLE (table6), spinbutton24, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label80 = gtk_label_new ("Color Selection");
  gtk_widget_set_name (label80, "label80");
  gtk_widget_show (label80);
  gtk_frame_set_label_widget (GTK_FRAME (frame19), label80);

  label75 = gtk_label_new ("Color selection");
  gtk_widget_set_name (label75, "label75");
  gtk_widget_show (label75);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label75);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame14, "frame14");
  gtk_widget_show (frame14);
  gtk_container_add (GTK_CONTAINER (notebook2), frame14);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox17, "vbox17");
  gtk_widget_show (vbox17);
  gtk_container_add (GTK_CONTAINER (frame14), vbox17);
  gtk_container_set_border_width (GTK_CONTAINER (vbox17), 4);

  table3 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox17), table3, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 7);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 9);

  frame16 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame16, "frame16");
  gtk_widget_show (frame16);
  gtk_table_attach (GTK_TABLE (table3), frame16, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (frame16, 80, 90);

  label66 = gtk_label_new ("");
  gtk_widget_set_name (label66, "label66");
  gtk_widget_show (label66);
  gtk_container_add (GTK_CONTAINER (frame16), label66);

  label65 = gtk_label_new ("Rectangle");
  gtk_widget_set_name (label65, "label65");
  gtk_widget_show (label65);
  gtk_frame_set_label_widget (GTK_FRAME (frame16), label65);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox18, "vbox18");
  gtk_widget_show (vbox18);
  gtk_table_attach (GTK_TABLE (table3), vbox18, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label64 = gtk_label_new ("Height");
  gtk_widget_set_name (label64, "label64");
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (vbox18), label64, FALSE, FALSE, 0);

  spinbutton15_adj = gtk_adjustment_new (50, 0, 100, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_set_name (spinbutton15, "spinbutton15");
  gtk_widget_show (spinbutton15);
  gtk_box_pack_start (GTK_BOX (vbox18), spinbutton15, FALSE, FALSE, 0);

  vbox20 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox20, "vbox20");
  gtk_widget_show (vbox20);
  gtk_table_attach (GTK_TABLE (table3), vbox20, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, "Black trace");
  gtk_widget_set_name (radiobutton11, "radiobutton11");
  gtk_widget_show (radiobutton11);
  gtk_box_pack_start (GTK_BOX (vbox20), radiobutton11, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, "White trace");
  gtk_widget_set_name (radiobutton12, "radiobutton12");
  gtk_widget_show (radiobutton12);
  gtk_box_pack_start (GTK_BOX (vbox20), radiobutton12, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox19, "vbox19");
  gtk_widget_show (vbox19);
  gtk_table_attach (GTK_TABLE (table3), vbox19, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label63 = gtk_label_new ("Width");
  gtk_widget_set_name (label63, "label63");
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (vbox19), label63, FALSE, FALSE, 0);

  spinbutton16_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_set_name (spinbutton16, "spinbutton16");
  gtk_widget_show (spinbutton16);
  gtk_box_pack_start (GTK_BOX (vbox19), spinbutton16, FALSE, FALSE, 0);

  label57 = gtk_label_new ("Color weighted mean");
  gtk_widget_set_name (label57, "label57");
  gtk_widget_show (label57);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label57);

  label49 = gtk_label_new ("Color weighted mean");
  gtk_widget_set_name (label49, "label49");
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label49);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame15, "frame15");
  gtk_widget_show (frame15);
  gtk_container_add (GTK_CONTAINER (notebook2), frame15);

  vbox21 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox21, "vbox21");
  gtk_widget_show (vbox21);
  gtk_container_add (GTK_CONTAINER (frame15), vbox21);
  gtk_container_set_border_width (GTK_CONTAINER (vbox21), 4);

  frame21 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame21, "frame21");
  gtk_widget_show (frame21);
  gtk_box_pack_start (GTK_BOX (vbox21), frame21, TRUE, TRUE, 0);

  vbox28 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox28, "vbox28");
  gtk_widget_show (vbox28);
  gtk_container_add (GTK_CONTAINER (frame21), vbox28);

  hbox13 = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox28), hbox13, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox13), 2);

  label90 = gtk_label_new ("Select Neural Net");
  gtk_widget_set_name (label90, "label90");
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox13), label90, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_set_name (button11, "button11");
  gtk_widget_show (button11);
  gtk_box_pack_start (GTK_BOX (hbox13), button11, FALSE, FALSE, 0);

  image109 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image109, "image109");
  gtk_widget_show (image109);
  gtk_container_add (GTK_CONTAINER (button11), image109);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox28), scrolledwindow2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow2), 5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_ETCHED_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_set_name (textview1, "textview1");
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview1);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), "Information about selected neural network.\n\nFeatures: Input, Output\nCode e Decode function.\n\nAgain, again\nand again . . .", -1);

  label84 = gtk_label_new ("None");
  gtk_widget_set_name (label84, "label84");
  gtk_widget_show (label84);
  gtk_frame_set_label_widget (GTK_FRAME (frame21), label84);

  frame17 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame17, "frame17");
  gtk_widget_show (frame17);
  gtk_box_pack_start (GTK_BOX (vbox21), frame17, FALSE, FALSE, 0);

  hbox11 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (frame17), hbox11);
  gtk_container_set_border_width (GTK_CONTAINER (hbox11), 4);

  checkbutton13 = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_set_name (checkbutton13, "checkbutton13");
  gtk_widget_show (checkbutton13);
  gtk_box_pack_start (GTK_BOX (hbox11), checkbutton13, FALSE, FALSE, 0);

  vbox22 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox22, "vbox22");
  gtk_widget_show (vbox22);
  gtk_box_pack_start (GTK_BOX (hbox11), vbox22, FALSE, TRUE, 0);

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, "Black trace");
  gtk_widget_set_name (radiobutton14, "radiobutton14");
  gtk_widget_show (radiobutton14);
  gtk_box_pack_start (GTK_BOX (vbox22), radiobutton14, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton15 = gtk_radio_button_new_with_mnemonic (NULL, "White trace");
  gtk_widget_set_name (radiobutton15, "radiobutton15");
  gtk_widget_show (radiobutton15);
  gtk_box_pack_start (GTK_BOX (vbox22), radiobutton15, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton15), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton15));

  hbox12 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (hbox11), hbox12, TRUE, TRUE, 0);

  label70 = gtk_label_new ("Thickness");
  gtk_widget_set_name (label70, "label70");
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox12), label70, FALSE, FALSE, 0);

  spinbutton17_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_set_name (spinbutton17, "spinbutton17");
  gtk_widget_show (spinbutton17);
  gtk_box_pack_start (GTK_BOX (hbox12), spinbutton17, FALSE, FALSE, 0);

  label71 = gtk_label_new ("Color snap");
  gtk_widget_set_name (label71, "label71");
  gtk_widget_show (label71);
  gtk_frame_set_label_widget (GTK_FRAME (frame17), label71);

  label59 = gtk_label_new ("Neural Network");
  gtk_widget_set_name (label59, "label59");
  gtk_widget_show (label59);
  gtk_frame_set_label_widget (GTK_FRAME (frame15), label59);

  label54 = gtk_label_new ("Neural Network");
  gtk_widget_set_name (label54, "label54");
  gtk_widget_show (label54);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label54);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar1, "statusbar1");
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) win_neuronteseo, "delete_event",
                    G_CALLBACK (on_win_neuronteseo_delete_event),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) preferences_2, "activate",
                    G_CALLBACK (on_preferences_w_activate),
                    NULL);
  g_signal_connect ((gpointer) path2, "activate",
                    G_CALLBACK (on_path2_activate),
                    NULL);
  g_signal_connect ((gpointer) dxf2, "activate",
                    G_CALLBACK (on_dxf2_activate),
                    NULL);
  g_signal_connect ((gpointer) trace2, "activate",
                    G_CALLBACK (on_trace2_activate),
                    NULL);
  g_signal_connect ((gpointer) sac2, "activate",
                    G_CALLBACK (on_sac2_activate),
                    NULL);
  g_signal_connect ((gpointer) sac_xy2, "activate",
                    G_CALLBACK (on_sac_xy2_activate),
                    NULL);
  g_signal_connect ((gpointer) sisma2, "activate",
                    G_CALLBACK (on_sisma2_activate),
                    NULL);
  g_signal_connect ((gpointer) timemark2, "activate",
                    G_CALLBACK (on_timemark2_activate),
                    NULL);
  g_signal_connect ((gpointer) path1, "activate",
                    G_CALLBACK (on_path1_activate),
                    NULL);
  g_signal_connect ((gpointer) dxf1, "activate",
                    G_CALLBACK (on_dxf1_activate),
                    NULL);
  g_signal_connect ((gpointer) trace1, "activate",
                    G_CALLBACK (on_track1_activate),
                    NULL);
  g_signal_connect ((gpointer) sac1, "activate",
                    G_CALLBACK (on_sac1_activate),
                    NULL);
  g_signal_connect ((gpointer) sac_xy1, "activate",
                    G_CALLBACK (on_sac_xy1_activate),
                    NULL);
  g_signal_connect ((gpointer) sisma1, "activate",
                    G_CALLBACK (on_sisma1_activate),
                    NULL);
  g_signal_connect ((gpointer) timemark1, "activate",
                    G_CALLBACK (on_timemark1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) resample1, "activate",
                    G_CALLBACK (on_resample1_activate),
                    NULL);
  g_signal_connect ((gpointer) align_all1, "activate",
                    G_CALLBACK (on_align_all1_activate),
                    NULL);
  g_signal_connect ((gpointer) link_all1, "activate",
                    G_CALLBACK (on_link_all1_activate),
                    NULL);
  g_signal_connect ((gpointer) move_and_rotation1, "activate",
                    G_CALLBACK (on_move_and_rotation1_activate),
                    NULL);
  g_signal_connect ((gpointer) fitting_polyline1, "activate",
                    G_CALLBACK (on_fitting_polyline1_activate),
                    NULL);
  g_signal_connect ((gpointer) fitting_bezier1, "activate",
                    G_CALLBACK (on_fitting_bezier1_activate),
                    NULL);
  g_signal_connect ((gpointer) recover_last2, "activate",
                    G_CALLBACK (on_recover_last2_activate),
                    NULL);
  g_signal_connect ((gpointer) evaluate_middle_tms1, "activate",
                    G_CALLBACK (on_evaluate_middle_tms1_activate),
                    NULL);
  g_signal_connect ((gpointer) adjustment1, "activate",
                    G_CALLBACK (on_adjustment1_activate),
                    NULL);
  g_signal_connect ((gpointer) info_window_1, "activate",
                    G_CALLBACK (on_info_window_1_activate),
                    NULL);
  g_signal_connect ((gpointer) help1, "activate",
                    G_CALLBACK (on_help1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_neuronteseo, win_neuronteseo, "win_neuronteseo");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, new1, "new1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, open1, "open1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, save1, "save1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, preferences_2, "preferences_2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image103, "image103");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, import1, "import1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image104, "image104");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, import1_menu, "import1_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, path2, "path2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, dxf2, "dxf2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, trace2, "trace2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sac2, "sac2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sac_xy2, "sac_xy2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sisma2, "sisma2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark2, "timemark2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, export1, "export1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image105, "image105");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, export1_menu, "export1_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, path1, "path1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, dxf1, "dxf1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, trace1, "trace1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sac1, "sac1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sac_xy1, "sac_xy1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sisma1, "sisma1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark1, "timemark1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, examples2, "examples2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, path3, "path3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, path3_menu, "path3_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, resample1, "resample1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, align_all1, "align_all1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, link_all1, "link_all1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, move_and_rotation1, "move_and_rotation1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, fitting_polyline1, "fitting_polyline1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, fitting_bezier1, "fitting_bezier1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, recover_last2, "recover_last2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark3, "timemark3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark3_menu, "timemark3_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, evaluate_middle_tms1, "evaluate_middle_tms1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, adjustment1, "adjustment1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, neural_network1, "neural_network1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, neural_network1_menu, "neural_network1_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, info_window_1, "info_window_1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image106, "image106");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, help1, "help1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image107, "image107");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, about1, "about1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image108, "image108");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button10, "button10");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton17, "radiobutton17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton18, "radiobutton18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button7, "button7");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button8, "button8");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, handlebox3, "handlebox3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button12, "button12");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button13, "button13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button14, "button14");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button15, "button15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox23, "vbox23");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame18, "frame18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table4, "table4");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label74, "label74");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton18, "spinbutton18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton19, "spinbutton19");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label73, "label73");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label72, "label72");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame22, "frame22");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label88, "label88");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label86, "label86");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame23, "frame23");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label89, "label89");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label87, "label87");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label55, "label55");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label48, "label48");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame19, "frame19");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox24, "vbox24");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table5, "table5");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame20, "frame20");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label76, "label76");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label77, "label77");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox25, "vbox25");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label78, "label78");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton20, "spinbutton20");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox27, "vbox27");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label79, "label79");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton21, "spinbutton21");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table6, "table6");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label81, "label81");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label82, "label82");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label83, "label83");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton22, "spinbutton22");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton23, "spinbutton23");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton24, "spinbutton24");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label80, "label80");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label75, "label75");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table3, "table3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame16, "frame16");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label66, "label66");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label65, "label65");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label64, "label64");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox20, "vbox20");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label63, "label63");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label57, "label57");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label49, "label49");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame15, "frame15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox21, "vbox21");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame21, "frame21");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox28, "vbox28");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label90, "label90");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button11, "button11");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image109, "image109");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label84, "label84");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame17, "frame17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, checkbutton13, "checkbutton13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox22, "vbox22");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton15, "radiobutton15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label70, "label70");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label71, "label71");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label59, "label59");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label54, "label54");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, statusbar1, "statusbar1");

  gtk_window_add_accel_group (GTK_WINDOW (win_neuronteseo), accel_group);

  return win_neuronteseo;
}

GtkWidget*
create_win_preferences (void)
{
  GtkWidget *win_preferences;
  GtkWidget *fixed2;
  GtkWidget *button6;
  GtkWidget *button5;
  GtkWidget *button4;
  GtkWidget *button3;
  GtkWidget *notebook1;
  GtkWidget *vbox8;
  GtkWidget *frame6;
  GtkWidget *vbox10;
  GtkWidget *label17;
  GtkWidget *frame5;
  GtkWidget *vbox9;
  GtkWidget *checkbutton_show_advice;
  GtkWidget *label15;
  GtkWidget *frame1;
  GtkWidget *vbox5;
  GtkWidget *checkbutton_reloc_origin;
  GtkWidget *checkbutton_autoresample;
  GtkWidget *label10;
  GtkWidget *label_General;
  GtkWidget *vbox2;
  GtkWidget *frame3;
  GtkWidget *vbox6;
  GtkWidget *checkbutton_direct_bezier;
  GtkWidget *label12;
  GtkWidget *frame4;
  GtkWidget *vbox7;
  GtkWidget *hbox3;
  GtkWidget *label14;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *checkbutton_ascendent;
  GtkWidget *hbox4;
  GtkWidget *checkbutton_autosave_tmppath;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label13;
  GtkWidget *frame2;
  GtkWidget *hbox1;
  GtkWidget *checkbutton_fitting;
  GtkWidget *vbox3;
  GtkWidget *radiobutton_polynomial;
  GSList *radiobutton_polynomial_group = NULL;
  GtkWidget *radiobutton_minimum_square;
  GtkWidget *hbox2;
  GtkWidget *label5;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *entry_svdfit;
  GtkWidget *entry_lfit;
  GtkWidget *label11;
  GtkWidget *label_Path;
  AtkObject *atko;

  win_preferences = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_preferences, "win_preferences");
  GTK_WIDGET_SET_FLAGS (win_preferences, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (win_preferences), "Preferences ...");
  gtk_window_set_modal (GTK_WINDOW (win_preferences), TRUE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_set_name (fixed2, "fixed2");
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (win_preferences), fixed2);
  GTK_WIDGET_SET_FLAGS (fixed2, GTK_CAN_FOCUS);

  button6 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (button6, "button6");
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 16, 360);
  gtk_widget_set_size_request (button6, 82, 31);

  button5 = gtk_button_new_from_stock ("gtk-save-as");
  gtk_widget_set_name (button5, "button5");
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 112, 360);
  gtk_widget_set_size_request (button5, 82, 31);

  button4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button4, "button4");
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 312, 360);
  gtk_widget_set_size_request (button4, 82, 31);

  button3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 400, 360);
  gtk_widget_set_size_request (button3, 82, 31);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 508, 356);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook1), TRUE);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox8);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame6, "frame6");
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox8), frame6, TRUE, TRUE, 0);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox10, "vbox10");
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (frame6), vbox10);
  gtk_container_set_border_width (GTK_CONTAINER (vbox10), 4);

  label17 = gtk_label_new ("Environment");
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label17);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame5, "frame5");
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox8), frame5, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox9, "vbox9");
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (frame5), vbox9);
  gtk_container_set_border_width (GTK_CONTAINER (vbox9), 4);

  checkbutton_show_advice = gtk_check_button_new_with_mnemonic ("Show advices");
  gtk_widget_set_name (checkbutton_show_advice, "checkbutton_show_advice");
  gtk_widget_show (checkbutton_show_advice);
  gtk_box_pack_start (GTK_BOX (vbox9), checkbutton_show_advice, FALSE, FALSE, 0);

  label15 = gtk_label_new ("Miscellaneous");
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label15);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox8), frame1, TRUE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (frame1), vbox5);
  gtk_container_set_border_width (GTK_CONTAINER (vbox5), 4);

  checkbutton_reloc_origin = gtk_check_button_new_with_mnemonic ("Export DXF path and timemark relocated in origin");
  gtk_widget_set_name (checkbutton_reloc_origin, "checkbutton_reloc_origin");
  gtk_widget_show (checkbutton_reloc_origin);
  gtk_box_pack_start (GTK_BOX (vbox5), checkbutton_reloc_origin, FALSE, FALSE, 0);

  checkbutton_autoresample = gtk_check_button_new_with_mnemonic ("Export DXF path with automatic resampling");
  gtk_widget_set_name (checkbutton_autoresample, "checkbutton_autoresample");
  gtk_widget_show (checkbutton_autoresample);
  gtk_box_pack_start (GTK_BOX (vbox5), checkbutton_autoresample, FALSE, FALSE, 0);

  label10 = gtk_label_new ("Export");
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label10);

  label_General = gtk_label_new ("General");
  gtk_widget_set_name (label_General, "label_General");
  gtk_widget_show (label_General);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label_General);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox2), frame3, TRUE, TRUE, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (frame3), vbox6);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 4);

  checkbutton_direct_bezier = gtk_check_button_new_with_mnemonic ("Return directly Bezier Path");
  gtk_widget_set_name (checkbutton_direct_bezier, "checkbutton_direct_bezier");
  gtk_widget_show (checkbutton_direct_bezier);
  gtk_box_pack_start (GTK_BOX (vbox6), checkbutton_direct_bezier, FALSE, FALSE, 0);

  label12 = gtk_label_new ("Miscellaneous");
  gtk_widget_set_name (label12, "label12");
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label12);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox2), frame4, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (frame4), vbox7);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 4);

  hbox3 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox3, TRUE, TRUE, 0);

  label14 = gtk_label_new ("Resampling step (pix)");
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 2);
  gtk_widget_set_name (spinbutton3, "spinbutton3");
  gtk_widget_show (spinbutton3);
  gtk_box_pack_start (GTK_BOX (hbox3), spinbutton3, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton3), TRUE);

  checkbutton_ascendent = gtk_check_button_new_with_mnemonic ("Constant abscissa ascendent");
  gtk_widget_set_name (checkbutton_ascendent, "checkbutton_ascendent");
  gtk_widget_show (checkbutton_ascendent);
  gtk_box_pack_start (GTK_BOX (vbox7), checkbutton_ascendent, FALSE, FALSE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox4, TRUE, TRUE, 0);

  checkbutton_autosave_tmppath = gtk_check_button_new_with_mnemonic ("Autosave temporary path every minutes");
  gtk_widget_set_name (checkbutton_autosave_tmppath, "checkbutton_autosave_tmppath");
  gtk_widget_show (checkbutton_autosave_tmppath);
  gtk_box_pack_start (GTK_BOX (hbox4), checkbutton_autosave_tmppath, FALSE, FALSE, 0);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_set_name (spinbutton4, "spinbutton4");
  gtk_widget_show (spinbutton4);
  gtk_box_pack_start (GTK_BOX (hbox4), spinbutton4, FALSE, TRUE, 0);

  label13 = gtk_label_new ("Resampling");
  gtk_widget_set_name (label13, "label13");
  gtk_widget_show (label13);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label13);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox2), frame2, FALSE, FALSE, 0);

  hbox1 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (frame2), hbox1);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 4);

  checkbutton_fitting = gtk_check_button_new_with_mnemonic ("Fitting");
  gtk_widget_set_name (checkbutton_fitting, "checkbutton_fitting");
  gtk_widget_show (checkbutton_fitting);
  gtk_box_pack_start (GTK_BOX (hbox1), checkbutton_fitting, FALSE, FALSE, 0);

  vbox3 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox3, FALSE, TRUE, 0);

  radiobutton_polynomial = gtk_radio_button_new_with_mnemonic (NULL, "Polynomial");
  gtk_widget_set_name (radiobutton_polynomial, "radiobutton_polynomial");
  gtk_widget_show (radiobutton_polynomial);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton_polynomial, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_polynomial), radiobutton_polynomial_group);
  radiobutton_polynomial_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_polynomial));

  radiobutton_minimum_square = gtk_radio_button_new_with_mnemonic (NULL, "Minimum Square");
  gtk_widget_set_name (radiobutton_minimum_square, "radiobutton_minimum_square");
  gtk_widget_show (radiobutton_minimum_square);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton_minimum_square, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_minimum_square), radiobutton_polynomial_group);
  radiobutton_polynomial_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_minimum_square));

  hbox2 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), hbox2, TRUE, TRUE, 0);

  label5 = gtk_label_new ("Order");
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_set_name (spinbutton1, "spinbutton1");
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox2), spinbutton1, FALSE, FALSE, 0);

  table1 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox1), table1, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 4);

  label6 = gtk_label_new ("SVDFIT");
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label7 = gtk_label_new ("LFIT");
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  label8 = gtk_label_new ("points");
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  label9 = gtk_label_new ("points");
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  entry_svdfit = gtk_entry_new ();
  gtk_widget_set_name (entry_svdfit, "entry_svdfit");
  gtk_widget_show (entry_svdfit);
  gtk_table_attach (GTK_TABLE (table1), entry_svdfit, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_svdfit, 60, -1);

  entry_lfit = gtk_entry_new ();
  gtk_widget_set_name (entry_lfit, "entry_lfit");
  gtk_widget_show (entry_lfit);
  gtk_table_attach (GTK_TABLE (table1), entry_lfit, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_lfit, 60, -1);

  label11 = gtk_label_new ("Fitting");
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label11);

  label_Path = gtk_label_new ("Adjustment");
  gtk_widget_set_name (label_Path, "label_Path");
  gtk_widget_show (label_Path);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label_Path);

  g_signal_connect ((gpointer) win_preferences, "delete_event",
                    G_CALLBACK (on_win_preferences_delete_event),
                    NULL);

  atko = gtk_widget_get_accessible (label_Path);
  atk_object_set_description (atko, "xxxxxxxxx");


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_preferences, win_preferences, "win_preferences");
  GLADE_HOOKUP_OBJECT (win_preferences, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (win_preferences, button6, "button6");
  GLADE_HOOKUP_OBJECT (win_preferences, button5, "button5");
  GLADE_HOOKUP_OBJECT (win_preferences, button4, "button4");
  GLADE_HOOKUP_OBJECT (win_preferences, button3, "button3");
  GLADE_HOOKUP_OBJECT (win_preferences, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (win_preferences, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (win_preferences, label17, "label17");
  GLADE_HOOKUP_OBJECT (win_preferences, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (win_preferences, checkbutton_show_advice, "checkbutton_show_advice");
  GLADE_HOOKUP_OBJECT (win_preferences, label15, "label15");
  GLADE_HOOKUP_OBJECT (win_preferences, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (win_preferences, checkbutton_reloc_origin, "checkbutton_reloc_origin");
  GLADE_HOOKUP_OBJECT (win_preferences, checkbutton_autoresample, "checkbutton_autoresample");
  GLADE_HOOKUP_OBJECT (win_preferences, label10, "label10");
  GLADE_HOOKUP_OBJECT (win_preferences, label_General, "label_General");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (win_preferences, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (win_preferences, checkbutton_direct_bezier, "checkbutton_direct_bezier");
  GLADE_HOOKUP_OBJECT (win_preferences, label12, "label12");
  GLADE_HOOKUP_OBJECT (win_preferences, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (win_preferences, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (win_preferences, label14, "label14");
  GLADE_HOOKUP_OBJECT (win_preferences, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (win_preferences, checkbutton_ascendent, "checkbutton_ascendent");
  GLADE_HOOKUP_OBJECT (win_preferences, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (win_preferences, checkbutton_autosave_tmppath, "checkbutton_autosave_tmppath");
  GLADE_HOOKUP_OBJECT (win_preferences, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (win_preferences, label13, "label13");
  GLADE_HOOKUP_OBJECT (win_preferences, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (win_preferences, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (win_preferences, checkbutton_fitting, "checkbutton_fitting");
  GLADE_HOOKUP_OBJECT (win_preferences, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (win_preferences, radiobutton_polynomial, "radiobutton_polynomial");
  GLADE_HOOKUP_OBJECT (win_preferences, radiobutton_minimum_square, "radiobutton_minimum_square");
  GLADE_HOOKUP_OBJECT (win_preferences, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (win_preferences, label5, "label5");
  GLADE_HOOKUP_OBJECT (win_preferences, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (win_preferences, table1, "table1");
  GLADE_HOOKUP_OBJECT (win_preferences, label6, "label6");
  GLADE_HOOKUP_OBJECT (win_preferences, label7, "label7");
  GLADE_HOOKUP_OBJECT (win_preferences, label8, "label8");
  GLADE_HOOKUP_OBJECT (win_preferences, label9, "label9");
  GLADE_HOOKUP_OBJECT (win_preferences, entry_svdfit, "entry_svdfit");
  GLADE_HOOKUP_OBJECT (win_preferences, entry_lfit, "entry_lfit");
  GLADE_HOOKUP_OBJECT (win_preferences, label11, "label11");
  GLADE_HOOKUP_OBJECT (win_preferences, label_Path, "label_Path");

  gtk_widget_grab_default (win_preferences);
  return win_preferences;
}

