/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_teseo (void);
GtkWidget* create_filechooser_import (void);
GtkWidget* create_dlg_about (void);
GtkWidget* create_dlg_session (void);
GtkWidget* create_filechooser_session (void);
GtkWidget* create_filechooser_export (void);
GtkWidget* create_win_curvature (void);
GtkWidget* create_dlg_parasites (void);
