/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_neuronteseo (void);
GtkWidget* create_filechooserimport (void);
GtkWidget* create_about_dlg (void);
GtkWidget* create_session_dlg (void);
GtkWidget* create_teseo_session_filechooser (void);
GtkWidget* create_window1 (void);
GtkWidget* create_preferences_dlg (void);
