/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "teseocallbacks.h"
#include "teseointerface.h"
#include "teseosupport.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_win_neuronteseo (void)
{
  GtkWidget *win_neuronteseo;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separator2;
  GtkWidget *preferences_2;
  GtkWidget *image135;
  GtkWidget *separator4;
  GtkWidget *import1;
  GtkWidget *image136;
  GtkWidget *import1_menu;
  GtkWidget *svg1;
  GtkWidget *dxf2;
  GtkWidget *trace2;
  GtkWidget *ascii1;
  GtkWidget *sac2;
  GtkWidget *sisma2;
  GtkWidget *timemark2;
  GtkWidget *separator6;
  GtkWidget *bezier1;
  GtkWidget *export1;
  GtkWidget *image137;
  GtkWidget *export1_menu;
  GtkWidget *svg2;
  GtkWidget *dxf1;
  GtkWidget *trace1;
  GtkWidget *ascii2;
  GtkWidget *sac1;
  GtkWidget *sisma1;
  GtkWidget *timemark1;
  GtkWidget *separator5;
  GtkWidget *examples2;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *path3;
  GtkWidget *path3_menu;
  GtkWidget *resample1;
  GtkWidget *align_all1;
  GtkWidget *link_all1;
  GtkWidget *move_and_rotation1;
  GtkWidget *fitting_polyline1;
  GtkWidget *fitting_bezier1;
  GtkWidget *recover_last2;
  GtkWidget *separator3;
  GtkWidget *timemark3;
  GtkWidget *timemark3_menu;
  GtkWidget *evaluate_middle_tms1;
  GtkWidget *adjustment1;
  GtkWidget *neural_network1;
  GtkWidget *neural_network1_menu;
  GtkWidget *info_window_1;
  GtkWidget *image138;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *help1;
  GtkWidget *image139;
  GtkWidget *about1;
  GtkWidget *image140;
  GtkWidget *handlebox2;
  GtkWidget *alignment1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *button10;
  GtkWidget *separatortoolitem1;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton10;
  GtkWidget *radiobutton9;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton17;
  GtkWidget *radiobutton18;
  GtkWidget *separatortoolitem2;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *handlebox3;
  GtkWidget *toolbar2;
  GtkWidget *button12;
  GtkWidget *button13;
  GtkWidget *button14;
  GtkWidget *button15;
  GtkWidget *hbox10;
  GtkWidget *notebook2;
  GtkWidget *frame13;
  GtkWidget *vbox23;
  GtkWidget *frame18;
  GtkWidget *table4;
  GtkWidget *label74;
  GtkObject *spinbutton18_adj;
  GtkWidget *spinbutton18;
  GtkObject *spinbutton19_adj;
  GtkWidget *spinbutton19;
  GtkWidget *label73;
  GtkWidget *label72;
  GtkWidget *frame22;
  GtkWidget *label88;
  GtkWidget *label86;
  GtkWidget *frame23;
  GtkWidget *label89;
  GtkWidget *label87;
  GtkWidget *label55;
  GtkWidget *label48;
  GtkWidget *frame19;
  GtkWidget *vbox24;
  GtkWidget *table5;
  GtkWidget *frame20;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *vbox25;
  GtkWidget *label78;
  GtkObject *spinbutton20_adj;
  GtkWidget *spinbutton20;
  GtkWidget *vbox27;
  GtkWidget *label79;
  GtkObject *spinbutton21_adj;
  GtkWidget *spinbutton21;
  GtkWidget *table6;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkObject *spinbutton22_adj;
  GtkWidget *spinbutton22;
  GtkObject *spinbutton23_adj;
  GtkWidget *spinbutton23;
  GtkObject *spinbutton24_adj;
  GtkWidget *spinbutton24;
  GtkWidget *label80;
  GtkWidget *label75;
  GtkWidget *frame14;
  GtkWidget *vbox17;
  GtkWidget *table3;
  GtkWidget *frame16;
  GtkWidget *label66;
  GtkWidget *label65;
  GtkWidget *vbox18;
  GtkWidget *label64;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkWidget *vbox20;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *radiobutton12;
  GtkWidget *vbox19;
  GtkWidget *label63;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *label57;
  GtkWidget *label49;
  GtkWidget *frame15;
  GtkWidget *vbox21;
  GtkWidget *frame21;
  GtkWidget *vbox28;
  GtkWidget *hbox13;
  GtkWidget *label90;
  GtkWidget *button11;
  GtkWidget *image109;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview1;
  GtkWidget *label84;
  GtkWidget *frame17;
  GtkWidget *hbox11;
  GtkWidget *checkbutton13;
  GtkWidget *vbox22;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton15;
  GtkWidget *hbox12;
  GtkWidget *label70;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkWidget *label71;
  GtkWidget *label59;
  GtkWidget *label54;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  win_neuronteseo = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_neuronteseo, "win_neuronteseo");
  gtk_window_set_title (GTK_WINDOW (win_neuronteseo), "Teseo 2.0");
  gtk_window_set_position (GTK_WINDOW (win_neuronteseo), GTK_WIN_POS_MOUSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (win_neuronteseo), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Session");
  gtk_widget_set_name (menuitem4, "menuitem4");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem4_menu, "menuitem4_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_set_name (new1, "new1");
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_set_name (open1, "open1");
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_set_name (save1, "save1");
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_set_name (save_as1, "save_as1");
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), save_as1);

  separator2 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator2, "separator2");
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  preferences_2 = gtk_image_menu_item_new_with_mnemonic ("_Preferences ...");
  gtk_widget_set_name (preferences_2, "preferences_2");
  gtk_widget_show (preferences_2);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), preferences_2);
  gtk_widget_add_accelerator (preferences_2, "activate", accel_group,
                              GDK_P, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image135 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image135, "image135");
  gtk_widget_show (image135);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (preferences_2), image135);

  separator4 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator4, "separator4");
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  import1 = gtk_image_menu_item_new_with_mnemonic ("_Import ...");
  gtk_widget_set_name (import1, "import1");
  gtk_widget_show (import1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), import1);

  image136 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image136, "image136");
  gtk_widget_show (image136);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (import1), image136);

  import1_menu = gtk_menu_new ();
  gtk_widget_set_name (import1_menu, "import1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (import1), import1_menu);

  svg1 = gtk_menu_item_new_with_mnemonic ("S_VG");
  gtk_widget_set_name (svg1, "svg1");
  gtk_widget_show (svg1);
  gtk_container_add (GTK_CONTAINER (import1_menu), svg1);

  dxf2 = gtk_menu_item_new_with_mnemonic ("_DXF");
  gtk_widget_set_name (dxf2, "dxf2");
  gtk_widget_show (dxf2);
  gtk_container_add (GTK_CONTAINER (import1_menu), dxf2);

  trace2 = gtk_menu_item_new_with_mnemonic ("_Trace");
  gtk_widget_set_name (trace2, "trace2");
  gtk_widget_show (trace2);
  gtk_container_add (GTK_CONTAINER (import1_menu), trace2);

  ascii1 = gtk_menu_item_new_with_mnemonic ("_ASCII");
  gtk_widget_set_name (ascii1, "ascii1");
  gtk_widget_show (ascii1);
  gtk_container_add (GTK_CONTAINER (import1_menu), ascii1);

  sac2 = gtk_menu_item_new_with_mnemonic ("_SAC");
  gtk_widget_set_name (sac2, "sac2");
  gtk_widget_show (sac2);
  gtk_container_add (GTK_CONTAINER (import1_menu), sac2);

  sisma2 = gtk_menu_item_new_with_mnemonic ("S_ISMA");
  gtk_widget_set_name (sisma2, "sisma2");
  gtk_widget_show (sisma2);
  gtk_container_add (GTK_CONTAINER (import1_menu), sisma2);

  timemark2 = gtk_menu_item_new_with_mnemonic ("_Timemark");
  gtk_widget_set_name (timemark2, "timemark2");
  gtk_widget_show (timemark2);
  gtk_container_add (GTK_CONTAINER (import1_menu), timemark2);

  separator6 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator6, "separator6");
  gtk_widget_show (separator6);
  gtk_container_add (GTK_CONTAINER (import1_menu), separator6);
  gtk_widget_set_sensitive (separator6, FALSE);

  bezier1 = gtk_menu_item_new_with_mnemonic ("Bezier");
  gtk_widget_set_name (bezier1, "bezier1");
  gtk_widget_show (bezier1);
  gtk_container_add (GTK_CONTAINER (import1_menu), bezier1);
  gtk_tooltips_set_tip (tooltips, bezier1, "Import old Bezier path GIMP 1.2", NULL);

  export1 = gtk_image_menu_item_new_with_mnemonic ("_Export ...");
  gtk_widget_set_name (export1, "export1");
  gtk_widget_show (export1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), export1);

  image137 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image137, "image137");
  gtk_widget_show (image137);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (export1), image137);

  export1_menu = gtk_menu_new ();
  gtk_widget_set_name (export1_menu, "export1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (export1), export1_menu);

  svg2 = gtk_menu_item_new_with_mnemonic ("S_VG");
  gtk_widget_set_name (svg2, "svg2");
  gtk_widget_show (svg2);
  gtk_container_add (GTK_CONTAINER (export1_menu), svg2);

  dxf1 = gtk_menu_item_new_with_mnemonic ("_DXF");
  gtk_widget_set_name (dxf1, "dxf1");
  gtk_widget_show (dxf1);
  gtk_container_add (GTK_CONTAINER (export1_menu), dxf1);

  trace1 = gtk_menu_item_new_with_mnemonic ("_Trace");
  gtk_widget_set_name (trace1, "trace1");
  gtk_widget_show (trace1);
  gtk_container_add (GTK_CONTAINER (export1_menu), trace1);

  ascii2 = gtk_menu_item_new_with_mnemonic ("_ASCII");
  gtk_widget_set_name (ascii2, "ascii2");
  gtk_widget_show (ascii2);
  gtk_container_add (GTK_CONTAINER (export1_menu), ascii2);

  sac1 = gtk_menu_item_new_with_mnemonic ("_SAC");
  gtk_widget_set_name (sac1, "sac1");
  gtk_widget_show (sac1);
  gtk_container_add (GTK_CONTAINER (export1_menu), sac1);

  sisma1 = gtk_menu_item_new_with_mnemonic ("S_ISMA");
  gtk_widget_set_name (sisma1, "sisma1");
  gtk_widget_show (sisma1);
  gtk_container_add (GTK_CONTAINER (export1_menu), sisma1);

  timemark1 = gtk_menu_item_new_with_mnemonic ("_Timemark");
  gtk_widget_set_name (timemark1, "timemark1");
  gtk_widget_show (timemark1);
  gtk_container_add (GTK_CONTAINER (export1_menu), timemark1);

  separator5 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator5, "separator5");
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (export1_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  examples2 = gtk_menu_item_new_with_mnemonic ("_Examples");
  gtk_widget_set_name (examples2, "examples2");
  gtk_widget_show (examples2);
  gtk_container_add (GTK_CONTAINER (export1_menu), examples2);
  gtk_widget_set_sensitive (examples2, FALSE);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quit1, "quit1");
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  path3 = gtk_menu_item_new_with_mnemonic ("_Path");
  gtk_widget_set_name (path3, "path3");
  gtk_widget_show (path3);
  gtk_container_add (GTK_CONTAINER (menubar1), path3);

  path3_menu = gtk_menu_new ();
  gtk_widget_set_name (path3_menu, "path3_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (path3), path3_menu);

  resample1 = gtk_menu_item_new_with_mnemonic ("R_esample");
  gtk_widget_set_name (resample1, "resample1");
  gtk_widget_show (resample1);
  gtk_container_add (GTK_CONTAINER (path3_menu), resample1);

  align_all1 = gtk_menu_item_new_with_mnemonic ("_Align All");
  gtk_widget_set_name (align_all1, "align_all1");
  gtk_widget_show (align_all1);
  gtk_container_add (GTK_CONTAINER (path3_menu), align_all1);

  link_all1 = gtk_menu_item_new_with_mnemonic ("_Link All");
  gtk_widget_set_name (link_all1, "link_all1");
  gtk_widget_show (link_all1);
  gtk_container_add (GTK_CONTAINER (path3_menu), link_all1);

  move_and_rotation1 = gtk_menu_item_new_with_mnemonic ("_Move and Rotation");
  gtk_widget_set_name (move_and_rotation1, "move_and_rotation1");
  gtk_widget_show (move_and_rotation1);
  gtk_container_add (GTK_CONTAINER (path3_menu), move_and_rotation1);

  fitting_polyline1 = gtk_menu_item_new_with_mnemonic ("Fitting _Polyline");
  gtk_widget_set_name (fitting_polyline1, "fitting_polyline1");
  gtk_widget_show (fitting_polyline1);
  gtk_container_add (GTK_CONTAINER (path3_menu), fitting_polyline1);

  fitting_bezier1 = gtk_menu_item_new_with_mnemonic ("Fitting _Bezier");
  gtk_widget_set_name (fitting_bezier1, "fitting_bezier1");
  gtk_widget_show (fitting_bezier1);
  gtk_container_add (GTK_CONTAINER (path3_menu), fitting_bezier1);

  recover_last2 = gtk_menu_item_new_with_mnemonic ("_Recover last");
  gtk_widget_set_name (recover_last2, "recover_last2");
  gtk_widget_show (recover_last2);
  gtk_container_add (GTK_CONTAINER (path3_menu), recover_last2);

  separator3 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator3, "separator3");
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (path3_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  timemark3 = gtk_menu_item_new_with_mnemonic ("_Timemark");
  gtk_widget_set_name (timemark3, "timemark3");
  gtk_widget_show (timemark3);
  gtk_container_add (GTK_CONTAINER (path3_menu), timemark3);

  timemark3_menu = gtk_menu_new ();
  gtk_widget_set_name (timemark3_menu, "timemark3_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (timemark3), timemark3_menu);

  evaluate_middle_tms1 = gtk_menu_item_new_with_mnemonic ("_Evaluate middle TMs");
  gtk_widget_set_name (evaluate_middle_tms1, "evaluate_middle_tms1");
  gtk_widget_show (evaluate_middle_tms1);
  gtk_container_add (GTK_CONTAINER (timemark3_menu), evaluate_middle_tms1);

  adjustment1 = gtk_menu_item_new_with_mnemonic ("_Adjustment");
  gtk_widget_set_name (adjustment1, "adjustment1");
  gtk_widget_show (adjustment1);
  gtk_container_add (GTK_CONTAINER (timemark3_menu), adjustment1);

  neural_network1 = gtk_menu_item_new_with_mnemonic ("_Neural Network");
  gtk_widget_set_name (neural_network1, "neural_network1");
  gtk_widget_show (neural_network1);
  gtk_container_add (GTK_CONTAINER (menubar1), neural_network1);

  neural_network1_menu = gtk_menu_new ();
  gtk_widget_set_name (neural_network1_menu, "neural_network1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (neural_network1), neural_network1_menu);

  info_window_1 = gtk_image_menu_item_new_with_mnemonic ("Info Window ...");
  gtk_widget_set_name (info_window_1, "info_window_1");
  gtk_widget_show (info_window_1);
  gtk_container_add (GTK_CONTAINER (neural_network1_menu), info_window_1);

  image138 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image138, "image138");
  gtk_widget_show (image138);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (info_window_1), image138);

  menuitem7 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_set_name (menuitem7, "menuitem7");
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem7_menu, "menuitem7_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  help1 = gtk_image_menu_item_new_with_mnemonic ("_Help ...");
  gtk_widget_set_name (help1, "help1");
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), help1);

  image139 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image139, "image139");
  gtk_widget_show (image139);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (help1), image139);

  about1 = gtk_image_menu_item_new_with_mnemonic ("_About ...");
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about1);

  image140 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image140, "image140");
  gtk_widget_show (image140);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image140);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox2, "handlebox2");
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, TRUE, TRUE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (handlebox2), alignment1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (alignment1), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar1), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-properties", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button10 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button10");
  gtk_widget_set_name (button10, "button10");
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (toolbar1), button10);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem1, "separatortoolitem1");
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  radiobutton10 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton10), "radiobutton10");
  tmp_image = gtk_image_new_from_stock ("gtk-redo", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton10), tmp_image);
  gtk_widget_set_name (radiobutton10, "radiobutton10");
  gtk_widget_show (radiobutton10);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton10);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton10));

  radiobutton9 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton9), "radiobutton9");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton9), tmp_image);
  gtk_widget_set_name (radiobutton9, "radiobutton9");
  gtk_widget_show (radiobutton9);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton9);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton9), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton9));
  gtk_toggle_tool_button_set_active (GTK_TOGGLE_TOOL_BUTTON (radiobutton9), TRUE);

  radiobutton8 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton8), "NN 1");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton8), tmp_image);
  gtk_widget_set_name (radiobutton8, "radiobutton8");
  gtk_widget_show (radiobutton8);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton8);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton8), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton8));

  radiobutton17 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton17), "NN 2");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton17), tmp_image);
  gtk_widget_set_name (radiobutton17, "radiobutton17");
  gtk_widget_show (radiobutton17);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton17);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton17), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton17));

  radiobutton18 = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiobutton18), "NN 3");
  tmp_image = create_pixmap (win_neuronteseo, "brain_mri_small.xpm");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiobutton18), tmp_image);
  gtk_widget_set_name (radiobutton18, "radiobutton18");
  gtk_widget_show (radiobutton18);
  gtk_container_add (GTK_CONTAINER (toolbar1), radiobutton18);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiobutton18), radiobutton10_group);
  radiobutton10_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiobutton18));

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem2, "separatortoolitem2");
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  tmp_image = gtk_image_new_from_stock ("gtk-go-back", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button7 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button7");
  gtk_widget_set_name (button7, "button7");
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (toolbar1), button7);

  tmp_image = gtk_image_new_from_stock ("gtk-go-forward", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button8 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button8");
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (toolbar1), button8);

  handlebox3 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox3, "handlebox3");
  gtk_widget_show (handlebox3);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox3, TRUE, TRUE, 0);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar2, "toolbar2");
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (handlebox3), toolbar2);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_ICONS);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar2), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button12 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button12");
  gtk_widget_set_name (button12, "button12");
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (toolbar2), button12);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button13 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button13");
  gtk_widget_set_name (button13, "button13");
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (toolbar2), button13);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button14 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button14");
  gtk_widget_set_name (button14, "button14");
  gtk_widget_show (button14);
  gtk_container_add (GTK_CONTAINER (toolbar2), button14);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button15 = (GtkWidget*) gtk_tool_button_new (tmp_image, "button15");
  gtk_widget_set_name (button15, "button15");
  gtk_widget_show (button15);
  gtk_container_add (GTK_CONTAINER (toolbar2), button15);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox10, TRUE, TRUE, 0);

  notebook2 = gtk_notebook_new ();
  gtk_widget_set_name (notebook2, "notebook2");
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (hbox10), notebook2, TRUE, TRUE, 0);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook2), GTK_POS_BOTTOM);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame13, "frame13");
  gtk_widget_show (frame13);
  gtk_container_add (GTK_CONTAINER (notebook2), frame13);

  vbox23 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox23, "vbox23");
  gtk_widget_show (vbox23);
  gtk_container_add (GTK_CONTAINER (frame13), vbox23);
  gtk_container_set_border_width (GTK_CONTAINER (vbox23), 4);

  frame18 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame18, "frame18");
  gtk_widget_show (frame18);
  gtk_box_pack_start (GTK_BOX (vbox23), frame18, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame18), 0, 0.25);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame18), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 4);

  label74 = gtk_label_new ("Back");
  gtk_widget_set_name (label74, "label74");
  gtk_widget_show (label74);
  gtk_table_attach (GTK_TABLE (table4), label74, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label74), 0, 0.5);

  spinbutton18_adj = gtk_adjustment_new (50, 0, 100, 1, 10, 10);
  spinbutton18 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton18_adj), 1, 0);
  gtk_widget_set_name (spinbutton18, "spinbutton18");
  gtk_widget_show (spinbutton18);
  gtk_table_attach (GTK_TABLE (table4), spinbutton18, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton19_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  spinbutton19 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton19_adj), 1, 0);
  gtk_widget_set_name (spinbutton19, "spinbutton19");
  gtk_widget_show (spinbutton19);
  gtk_table_attach (GTK_TABLE (table4), spinbutton19, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label73 = gtk_label_new ("Forward");
  gtk_widget_set_name (label73, "label73");
  gtk_widget_show (label73);
  gtk_table_attach (GTK_TABLE (table4), label73, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label73), 0, 0.5);

  label72 = gtk_label_new ("Execution Steps");
  gtk_widget_set_name (label72, "label72");
  gtk_widget_show (label72);
  gtk_frame_set_label_widget (GTK_FRAME (frame18), label72);

  frame22 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame22, "frame22");
  gtk_widget_show (frame22);
  gtk_box_pack_start (GTK_BOX (vbox23), frame22, TRUE, TRUE, 0);

  label88 = gtk_label_new ("label88");
  gtk_widget_set_name (label88, "label88");
  gtk_widget_show (label88);
  gtk_container_add (GTK_CONTAINER (frame22), label88);

  label86 = gtk_label_new ("label86");
  gtk_widget_set_name (label86, "label86");
  gtk_widget_show (label86);
  gtk_frame_set_label_widget (GTK_FRAME (frame22), label86);

  frame23 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame23, "frame23");
  gtk_widget_show (frame23);
  gtk_box_pack_start (GTK_BOX (vbox23), frame23, TRUE, TRUE, 0);

  label89 = gtk_label_new ("label89");
  gtk_widget_set_name (label89, "label89");
  gtk_widget_show (label89);
  gtk_container_add (GTK_CONTAINER (frame23), label89);

  label87 = gtk_label_new ("label87");
  gtk_widget_set_name (label87, "label87");
  gtk_widget_show (label87);
  gtk_frame_set_label_widget (GTK_FRAME (frame23), label87);

  label55 = gtk_label_new ("General");
  gtk_widget_set_name (label55, "label55");
  gtk_widget_show (label55);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label55);

  label48 = gtk_label_new ("General");
  gtk_widget_set_name (label48, "label48");
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label48);

  frame19 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame19, "frame19");
  gtk_widget_show (frame19);
  gtk_container_add (GTK_CONTAINER (notebook2), frame19);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox24, "vbox24");
  gtk_widget_show (vbox24);
  gtk_container_add (GTK_CONTAINER (frame19), vbox24);
  gtk_container_set_border_width (GTK_CONTAINER (vbox24), 4);

  table5 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table5, "table5");
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (vbox24), table5, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 7);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 9);

  frame20 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame20, "frame20");
  gtk_widget_show (frame20);
  gtk_table_attach (GTK_TABLE (table5), frame20, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (frame20, 80, 90);

  label76 = gtk_label_new ("");
  gtk_widget_set_name (label76, "label76");
  gtk_widget_show (label76);
  gtk_container_add (GTK_CONTAINER (frame20), label76);

  label77 = gtk_label_new ("Rectangle");
  gtk_widget_set_name (label77, "label77");
  gtk_widget_show (label77);
  gtk_frame_set_label_widget (GTK_FRAME (frame20), label77);

  vbox25 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox25, "vbox25");
  gtk_widget_show (vbox25);
  gtk_table_attach (GTK_TABLE (table5), vbox25, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label78 = gtk_label_new ("Height");
  gtk_widget_set_name (label78, "label78");
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (vbox25), label78, FALSE, FALSE, 0);

  spinbutton20_adj = gtk_adjustment_new (50, 0, 100, 1, 10, 10);
  spinbutton20 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton20_adj), 1, 0);
  gtk_widget_set_name (spinbutton20, "spinbutton20");
  gtk_widget_show (spinbutton20);
  gtk_box_pack_start (GTK_BOX (vbox25), spinbutton20, FALSE, FALSE, 0);

  vbox27 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox27, "vbox27");
  gtk_widget_show (vbox27);
  gtk_table_attach (GTK_TABLE (table5), vbox27, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label79 = gtk_label_new ("Width");
  gtk_widget_set_name (label79, "label79");
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (vbox27), label79, FALSE, FALSE, 0);

  spinbutton21_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  spinbutton21 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton21_adj), 1, 0);
  gtk_widget_set_name (spinbutton21, "spinbutton21");
  gtk_widget_show (spinbutton21);
  gtk_box_pack_start (GTK_BOX (vbox27), spinbutton21, FALSE, FALSE, 0);

  table6 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table6, "table6");
  gtk_widget_show (table6);
  gtk_table_attach (GTK_TABLE (table5), table6, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 12);

  label81 = gtk_label_new ("Low Color");
  gtk_widget_set_name (label81, "label81");
  gtk_widget_show (label81);
  gtk_table_attach (GTK_TABLE (table6), label81, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label81), 0, 0.5);

  label82 = gtk_label_new ("Trace Color");
  gtk_widget_set_name (label82, "label82");
  gtk_widget_show (label82);
  gtk_table_attach (GTK_TABLE (table6), label82, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label82), 0, 0.5);

  label83 = gtk_label_new ("High Color");
  gtk_widget_set_name (label83, "label83");
  gtk_widget_show (label83);
  gtk_table_attach (GTK_TABLE (table6), label83, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label83), 0, 0.5);

  spinbutton22_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton22 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton22_adj), 1, 0);
  gtk_widget_set_name (spinbutton22, "spinbutton22");
  gtk_widget_show (spinbutton22);
  gtk_table_attach (GTK_TABLE (table6), spinbutton22, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton23_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton23 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton23_adj), 1, 0);
  gtk_widget_set_name (spinbutton23, "spinbutton23");
  gtk_widget_show (spinbutton23);
  gtk_table_attach (GTK_TABLE (table6), spinbutton23, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton24_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton24 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton24_adj), 1, 0);
  gtk_widget_set_name (spinbutton24, "spinbutton24");
  gtk_widget_show (spinbutton24);
  gtk_table_attach (GTK_TABLE (table6), spinbutton24, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label80 = gtk_label_new ("Color Selection");
  gtk_widget_set_name (label80, "label80");
  gtk_widget_show (label80);
  gtk_frame_set_label_widget (GTK_FRAME (frame19), label80);

  label75 = gtk_label_new ("Color selection");
  gtk_widget_set_name (label75, "label75");
  gtk_widget_show (label75);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label75);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame14, "frame14");
  gtk_widget_show (frame14);
  gtk_container_add (GTK_CONTAINER (notebook2), frame14);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox17, "vbox17");
  gtk_widget_show (vbox17);
  gtk_container_add (GTK_CONTAINER (frame14), vbox17);
  gtk_container_set_border_width (GTK_CONTAINER (vbox17), 4);

  table3 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox17), table3, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 7);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 9);

  frame16 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame16, "frame16");
  gtk_widget_show (frame16);
  gtk_table_attach (GTK_TABLE (table3), frame16, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (frame16, 80, 90);

  label66 = gtk_label_new ("");
  gtk_widget_set_name (label66, "label66");
  gtk_widget_show (label66);
  gtk_container_add (GTK_CONTAINER (frame16), label66);

  label65 = gtk_label_new ("Rectangle");
  gtk_widget_set_name (label65, "label65");
  gtk_widget_show (label65);
  gtk_frame_set_label_widget (GTK_FRAME (frame16), label65);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox18, "vbox18");
  gtk_widget_show (vbox18);
  gtk_table_attach (GTK_TABLE (table3), vbox18, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label64 = gtk_label_new ("Height");
  gtk_widget_set_name (label64, "label64");
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (vbox18), label64, FALSE, FALSE, 0);

  spinbutton15_adj = gtk_adjustment_new (50, 0, 100, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_set_name (spinbutton15, "spinbutton15");
  gtk_widget_show (spinbutton15);
  gtk_box_pack_start (GTK_BOX (vbox18), spinbutton15, FALSE, FALSE, 0);

  vbox20 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox20, "vbox20");
  gtk_widget_show (vbox20);
  gtk_table_attach (GTK_TABLE (table3), vbox20, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, "Black trace");
  gtk_widget_set_name (radiobutton11, "radiobutton11");
  gtk_widget_show (radiobutton11);
  gtk_box_pack_start (GTK_BOX (vbox20), radiobutton11, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, "White trace");
  gtk_widget_set_name (radiobutton12, "radiobutton12");
  gtk_widget_show (radiobutton12);
  gtk_box_pack_start (GTK_BOX (vbox20), radiobutton12, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox19, "vbox19");
  gtk_widget_show (vbox19);
  gtk_table_attach (GTK_TABLE (table3), vbox19, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label63 = gtk_label_new ("Width");
  gtk_widget_set_name (label63, "label63");
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (vbox19), label63, FALSE, FALSE, 0);

  spinbutton16_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_set_name (spinbutton16, "spinbutton16");
  gtk_widget_show (spinbutton16);
  gtk_box_pack_start (GTK_BOX (vbox19), spinbutton16, FALSE, FALSE, 0);

  label57 = gtk_label_new ("Color weighted mean");
  gtk_widget_set_name (label57, "label57");
  gtk_widget_show (label57);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label57);

  label49 = gtk_label_new ("Color weighted mean");
  gtk_widget_set_name (label49, "label49");
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label49);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame15, "frame15");
  gtk_widget_show (frame15);
  gtk_container_add (GTK_CONTAINER (notebook2), frame15);

  vbox21 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox21, "vbox21");
  gtk_widget_show (vbox21);
  gtk_container_add (GTK_CONTAINER (frame15), vbox21);
  gtk_container_set_border_width (GTK_CONTAINER (vbox21), 4);

  frame21 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame21, "frame21");
  gtk_widget_show (frame21);
  gtk_box_pack_start (GTK_BOX (vbox21), frame21, TRUE, TRUE, 0);

  vbox28 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox28, "vbox28");
  gtk_widget_show (vbox28);
  gtk_container_add (GTK_CONTAINER (frame21), vbox28);

  hbox13 = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox28), hbox13, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox13), 2);

  label90 = gtk_label_new ("Select Neural Net");
  gtk_widget_set_name (label90, "label90");
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox13), label90, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_set_name (button11, "button11");
  gtk_widget_show (button11);
  gtk_box_pack_start (GTK_BOX (hbox13), button11, FALSE, FALSE, 0);

  image109 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image109, "image109");
  gtk_widget_show (image109);
  gtk_container_add (GTK_CONTAINER (button11), image109);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox28), scrolledwindow2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow2), 5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_ETCHED_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_set_name (textview1, "textview1");
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview1);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), "Information about selected neural network.\n\nFeatures: Input, Output\nCode e Decode function.\n\nAgain, again\nand again . . .", -1);

  label84 = gtk_label_new ("None");
  gtk_widget_set_name (label84, "label84");
  gtk_widget_show (label84);
  gtk_frame_set_label_widget (GTK_FRAME (frame21), label84);

  frame17 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame17, "frame17");
  gtk_widget_show (frame17);
  gtk_box_pack_start (GTK_BOX (vbox21), frame17, FALSE, FALSE, 0);

  hbox11 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (frame17), hbox11);
  gtk_container_set_border_width (GTK_CONTAINER (hbox11), 4);

  checkbutton13 = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_set_name (checkbutton13, "checkbutton13");
  gtk_widget_show (checkbutton13);
  gtk_box_pack_start (GTK_BOX (hbox11), checkbutton13, FALSE, FALSE, 0);

  vbox22 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox22, "vbox22");
  gtk_widget_show (vbox22);
  gtk_box_pack_start (GTK_BOX (hbox11), vbox22, FALSE, TRUE, 0);

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, "Black trace");
  gtk_widget_set_name (radiobutton14, "radiobutton14");
  gtk_widget_show (radiobutton14);
  gtk_box_pack_start (GTK_BOX (vbox22), radiobutton14, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton15 = gtk_radio_button_new_with_mnemonic (NULL, "White trace");
  gtk_widget_set_name (radiobutton15, "radiobutton15");
  gtk_widget_show (radiobutton15);
  gtk_box_pack_start (GTK_BOX (vbox22), radiobutton15, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton15), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton15));

  hbox12 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (hbox11), hbox12, TRUE, TRUE, 0);

  label70 = gtk_label_new ("Thickness");
  gtk_widget_set_name (label70, "label70");
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox12), label70, FALSE, FALSE, 0);

  spinbutton17_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_set_name (spinbutton17, "spinbutton17");
  gtk_widget_show (spinbutton17);
  gtk_box_pack_start (GTK_BOX (hbox12), spinbutton17, FALSE, FALSE, 0);

  label71 = gtk_label_new ("Color snap");
  gtk_widget_set_name (label71, "label71");
  gtk_widget_show (label71);
  gtk_frame_set_label_widget (GTK_FRAME (frame17), label71);

  label59 = gtk_label_new ("Neural Network");
  gtk_widget_set_name (label59, "label59");
  gtk_widget_show (label59);
  gtk_frame_set_label_widget (GTK_FRAME (frame15), label59);

  label54 = gtk_label_new ("Neural Network");
  gtk_widget_set_name (label54, "label54");
  gtk_widget_show (label54);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label54);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar1, "statusbar1");
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) win_neuronteseo, "delete_event",
                    G_CALLBACK (on_win_neuronteseo_delete_event),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) preferences_2, "activate",
                    G_CALLBACK (on_preferences_w_activate),
                    NULL);
  g_signal_connect ((gpointer) svg1, "activate",
                    G_CALLBACK (on_svg1_activate),
                    NULL);
  g_signal_connect ((gpointer) dxf2, "activate",
                    G_CALLBACK (on_dxf2_activate),
                    NULL);
  g_signal_connect ((gpointer) trace2, "activate",
                    G_CALLBACK (on_trace2_activate),
                    NULL);
  g_signal_connect ((gpointer) ascii1, "activate",
                    G_CALLBACK (on_ascii1_activate),
                    NULL);
  g_signal_connect ((gpointer) sac2, "activate",
                    G_CALLBACK (on_sac2_activate),
                    NULL);
  g_signal_connect ((gpointer) sisma2, "activate",
                    G_CALLBACK (on_sisma2_activate),
                    NULL);
  g_signal_connect ((gpointer) timemark2, "activate",
                    G_CALLBACK (on_timemark2_activate),
                    NULL);
  g_signal_connect ((gpointer) bezier1, "activate",
                    G_CALLBACK (on_bezier1_activate),
                    NULL);
  g_signal_connect ((gpointer) svg2, "activate",
                    G_CALLBACK (on_svg2_activate),
                    NULL);
  g_signal_connect ((gpointer) dxf1, "activate",
                    G_CALLBACK (on_dxf1_activate),
                    NULL);
  g_signal_connect ((gpointer) trace1, "activate",
                    G_CALLBACK (on_track1_activate),
                    NULL);
  g_signal_connect ((gpointer) ascii2, "activate",
                    G_CALLBACK (on_ascii2_activate),
                    NULL);
  g_signal_connect ((gpointer) sac1, "activate",
                    G_CALLBACK (on_sac1_activate),
                    NULL);
  g_signal_connect ((gpointer) sisma1, "activate",
                    G_CALLBACK (on_sisma1_activate),
                    NULL);
  g_signal_connect ((gpointer) timemark1, "activate",
                    G_CALLBACK (on_timemark1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) resample1, "activate",
                    G_CALLBACK (on_resample1_activate),
                    NULL);
  g_signal_connect ((gpointer) align_all1, "activate",
                    G_CALLBACK (on_align_all1_activate),
                    NULL);
  g_signal_connect ((gpointer) link_all1, "activate",
                    G_CALLBACK (on_link_all1_activate),
                    NULL);
  g_signal_connect ((gpointer) move_and_rotation1, "activate",
                    G_CALLBACK (on_move_and_rotation1_activate),
                    NULL);
  g_signal_connect ((gpointer) fitting_polyline1, "activate",
                    G_CALLBACK (on_fitting_polyline1_activate),
                    NULL);
  g_signal_connect ((gpointer) fitting_bezier1, "activate",
                    G_CALLBACK (on_fitting_bezier1_activate),
                    NULL);
  g_signal_connect ((gpointer) recover_last2, "activate",
                    G_CALLBACK (on_recover_last2_activate),
                    NULL);
  g_signal_connect ((gpointer) evaluate_middle_tms1, "activate",
                    G_CALLBACK (on_evaluate_middle_tms1_activate),
                    NULL);
  g_signal_connect ((gpointer) adjustment1, "activate",
                    G_CALLBACK (on_adjustment1_activate),
                    NULL);
  g_signal_connect ((gpointer) info_window_1, "activate",
                    G_CALLBACK (on_info_window_1_activate),
                    NULL);
  g_signal_connect ((gpointer) help1, "activate",
                    G_CALLBACK (on_help1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_neuronteseo, win_neuronteseo, "win_neuronteseo");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, new1, "new1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, open1, "open1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, save1, "save1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, preferences_2, "preferences_2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image135, "image135");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, import1, "import1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image136, "image136");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, import1_menu, "import1_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, svg1, "svg1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, dxf2, "dxf2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, trace2, "trace2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, ascii1, "ascii1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sac2, "sac2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sisma2, "sisma2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark2, "timemark2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator6, "separator6");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, bezier1, "bezier1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, export1, "export1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image137, "image137");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, export1_menu, "export1_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, svg2, "svg2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, dxf1, "dxf1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, trace1, "trace1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, ascii2, "ascii2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sac1, "sac1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, sisma1, "sisma1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark1, "timemark1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, examples2, "examples2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, path3, "path3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, path3_menu, "path3_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, resample1, "resample1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, align_all1, "align_all1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, link_all1, "link_all1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, move_and_rotation1, "move_and_rotation1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, fitting_polyline1, "fitting_polyline1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, fitting_bezier1, "fitting_bezier1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, recover_last2, "recover_last2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark3, "timemark3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, timemark3_menu, "timemark3_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, evaluate_middle_tms1, "evaluate_middle_tms1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, adjustment1, "adjustment1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, neural_network1, "neural_network1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, neural_network1_menu, "neural_network1_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, info_window_1, "info_window_1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image138, "image138");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, help1, "help1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image139, "image139");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, about1, "about1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image140, "image140");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button10, "button10");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton17, "radiobutton17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton18, "radiobutton18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button7, "button7");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button8, "button8");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, handlebox3, "handlebox3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button12, "button12");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button13, "button13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button14, "button14");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button15, "button15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox23, "vbox23");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame18, "frame18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table4, "table4");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label74, "label74");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton18, "spinbutton18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton19, "spinbutton19");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label73, "label73");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label72, "label72");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame22, "frame22");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label88, "label88");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label86, "label86");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame23, "frame23");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label89, "label89");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label87, "label87");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label55, "label55");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label48, "label48");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame19, "frame19");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox24, "vbox24");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table5, "table5");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame20, "frame20");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label76, "label76");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label77, "label77");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox25, "vbox25");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label78, "label78");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton20, "spinbutton20");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox27, "vbox27");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label79, "label79");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton21, "spinbutton21");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table6, "table6");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label81, "label81");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label82, "label82");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label83, "label83");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton22, "spinbutton22");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton23, "spinbutton23");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton24, "spinbutton24");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label80, "label80");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label75, "label75");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, table3, "table3");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame16, "frame16");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label66, "label66");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label65, "label65");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label64, "label64");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox20, "vbox20");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label63, "label63");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label57, "label57");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label49, "label49");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame15, "frame15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox21, "vbox21");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame21, "frame21");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox28, "vbox28");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label90, "label90");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, button11, "button11");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, image109, "image109");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label84, "label84");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, frame17, "frame17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, checkbutton13, "checkbutton13");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, vbox22, "vbox22");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, radiobutton15, "radiobutton15");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label70, "label70");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label71, "label71");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label59, "label59");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, label54, "label54");
  GLADE_HOOKUP_OBJECT (win_neuronteseo, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (win_neuronteseo, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (win_neuronteseo), accel_group);

  return win_neuronteseo;
}

GtkWidget*
create_filechooserimport (void)
{
  GtkWidget *filechooserimport;
  GtkWidget *dialog_vbox4;
  GtkWidget *dialog_action_area4;
  GtkWidget *button16;
  GtkWidget *button17;

  filechooserimport = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_widget_set_name (filechooserimport, "filechooserimport");
  gtk_window_set_type_hint (GTK_WINDOW (filechooserimport), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (filechooserimport)->vbox;
  gtk_widget_set_name (dialog_vbox4, "dialog_vbox4");
  gtk_widget_show (dialog_vbox4);

  dialog_action_area4 = GTK_DIALOG (filechooserimport)->action_area;
  gtk_widget_set_name (dialog_action_area4, "dialog_action_area4");
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  button16 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button16, "button16");
  gtk_widget_show (button16);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserimport), button16, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (button17, "button17");
  gtk_widget_show (button17);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserimport), button17, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserimport, filechooserimport, "filechooserimport");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserimport, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserimport, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (filechooserimport, button16, "button16");
  GLADE_HOOKUP_OBJECT (filechooserimport, button17, "button17");

  gtk_widget_grab_default (button17);
  return filechooserimport;
}

GtkWidget*
create_preferences_dlg (void)
{
  GtkWidget *preferences_dlg;
  GtkWidget *dialog_vbox5;
  GtkWidget *notebook3;
  GtkWidget *vbox55;
  GtkWidget *frame44;
  GtkWidget *vbox56;
  GtkWidget *label147;
  GtkWidget *frame45;
  GtkWidget *vbox57;
  GtkWidget *checkbutton26;
  GtkWidget *label148;
  GtkWidget *frame46;
  GtkWidget *vbox58;
  GtkWidget *checkbutton27;
  GtkWidget *checkbutton28;
  GtkWidget *label149;
  GtkWidget *label150;
  GtkWidget *vbox59;
  GtkWidget *frame47;
  GtkWidget *vbox60;
  GtkWidget *checkbutton29;
  GtkWidget *label151;
  GtkWidget *frame48;
  GtkWidget *vbox61;
  GtkWidget *hbox23;
  GtkWidget *label152;
  GtkObject *spinbutton38_adj;
  GtkWidget *spinbutton38;
  GtkWidget *checkbutton30;
  GtkWidget *hbox24;
  GtkWidget *checkbutton31;
  GtkObject *spinbutton39_adj;
  GtkWidget *spinbutton39;
  GtkWidget *label153;
  GtkWidget *frame49;
  GtkWidget *hbox25;
  GtkWidget *checkbutton32;
  GtkWidget *vbox62;
  GtkWidget *radiobutton24;
  GSList *radiobutton24_group = NULL;
  GtkWidget *radiobutton25;
  GSList *radiobutton25_group = NULL;
  GtkWidget *hbox26;
  GtkWidget *label154;
  GtkObject *spinbutton40_adj;
  GtkWidget *spinbutton40;
  GtkWidget *table10;
  GtkWidget *label155;
  GtkWidget *label156;
  GtkWidget *label157;
  GtkWidget *label158;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label159;
  GtkWidget *label160;
  GtkWidget *dialog_action_area6;
  GtkWidget *applybutton1;
  GtkWidget *cancelbutton3;
  GtkWidget *okbutton3;

  preferences_dlg = gtk_dialog_new ();
  gtk_widget_set_name (preferences_dlg, "preferences_dlg");
  gtk_window_set_title (GTK_WINDOW (preferences_dlg), "Preferences...");
  gtk_window_set_type_hint (GTK_WINDOW (preferences_dlg), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox5 = GTK_DIALOG (preferences_dlg)->vbox;
  gtk_widget_set_name (dialog_vbox5, "dialog_vbox5");
  gtk_widget_show (dialog_vbox5);

  notebook3 = gtk_notebook_new ();
  gtk_widget_set_name (notebook3, "notebook3");
  gtk_widget_show (notebook3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), notebook3, TRUE, TRUE, 0);
  gtk_widget_set_size_request (notebook3, 508, 356);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook3), TRUE);

  vbox55 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox55, "vbox55");
  gtk_widget_show (vbox55);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox55);

  frame44 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame44, "frame44");
  gtk_widget_show (frame44);
  gtk_box_pack_start (GTK_BOX (vbox55), frame44, TRUE, TRUE, 0);

  vbox56 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox56, "vbox56");
  gtk_widget_show (vbox56);
  gtk_container_add (GTK_CONTAINER (frame44), vbox56);
  gtk_container_set_border_width (GTK_CONTAINER (vbox56), 4);

  label147 = gtk_label_new ("Environment");
  gtk_widget_set_name (label147, "label147");
  gtk_widget_show (label147);
  gtk_frame_set_label_widget (GTK_FRAME (frame44), label147);

  frame45 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame45, "frame45");
  gtk_widget_show (frame45);
  gtk_box_pack_start (GTK_BOX (vbox55), frame45, TRUE, TRUE, 0);

  vbox57 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox57, "vbox57");
  gtk_widget_show (vbox57);
  gtk_container_add (GTK_CONTAINER (frame45), vbox57);
  gtk_container_set_border_width (GTK_CONTAINER (vbox57), 4);

  checkbutton26 = gtk_check_button_new_with_mnemonic ("Show advices");
  gtk_widget_set_name (checkbutton26, "checkbutton26");
  gtk_widget_show (checkbutton26);
  gtk_box_pack_start (GTK_BOX (vbox57), checkbutton26, FALSE, FALSE, 0);

  label148 = gtk_label_new ("Miscellaneous");
  gtk_widget_set_name (label148, "label148");
  gtk_widget_show (label148);
  gtk_frame_set_label_widget (GTK_FRAME (frame45), label148);

  frame46 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame46, "frame46");
  gtk_widget_show (frame46);
  gtk_box_pack_start (GTK_BOX (vbox55), frame46, TRUE, TRUE, 0);

  vbox58 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox58, "vbox58");
  gtk_widget_show (vbox58);
  gtk_container_add (GTK_CONTAINER (frame46), vbox58);
  gtk_container_set_border_width (GTK_CONTAINER (vbox58), 4);

  checkbutton27 = gtk_check_button_new_with_mnemonic ("Export DXF path and timemark relocated in origin");
  gtk_widget_set_name (checkbutton27, "checkbutton27");
  gtk_widget_show (checkbutton27);
  gtk_box_pack_start (GTK_BOX (vbox58), checkbutton27, FALSE, FALSE, 0);

  checkbutton28 = gtk_check_button_new_with_mnemonic ("Export DXF path with automatic resampling");
  gtk_widget_set_name (checkbutton28, "checkbutton28");
  gtk_widget_show (checkbutton28);
  gtk_box_pack_start (GTK_BOX (vbox58), checkbutton28, FALSE, FALSE, 0);

  label149 = gtk_label_new ("Export");
  gtk_widget_set_name (label149, "label149");
  gtk_widget_show (label149);
  gtk_frame_set_label_widget (GTK_FRAME (frame46), label149);

  label150 = gtk_label_new ("General");
  gtk_widget_set_name (label150, "label150");
  gtk_widget_show (label150);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label150);

  vbox59 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox59, "vbox59");
  gtk_widget_show (vbox59);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox59);

  frame47 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame47, "frame47");
  gtk_widget_show (frame47);
  gtk_box_pack_start (GTK_BOX (vbox59), frame47, TRUE, TRUE, 0);

  vbox60 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox60, "vbox60");
  gtk_widget_show (vbox60);
  gtk_container_add (GTK_CONTAINER (frame47), vbox60);
  gtk_container_set_border_width (GTK_CONTAINER (vbox60), 4);

  checkbutton29 = gtk_check_button_new_with_mnemonic ("Return directly Bezier Path");
  gtk_widget_set_name (checkbutton29, "checkbutton29");
  gtk_widget_show (checkbutton29);
  gtk_box_pack_start (GTK_BOX (vbox60), checkbutton29, FALSE, FALSE, 0);

  label151 = gtk_label_new ("Miscellaneous");
  gtk_widget_set_name (label151, "label151");
  gtk_widget_show (label151);
  gtk_frame_set_label_widget (GTK_FRAME (frame47), label151);

  frame48 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame48, "frame48");
  gtk_widget_show (frame48);
  gtk_box_pack_start (GTK_BOX (vbox59), frame48, TRUE, TRUE, 0);

  vbox61 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox61, "vbox61");
  gtk_widget_show (vbox61);
  gtk_container_add (GTK_CONTAINER (frame48), vbox61);
  gtk_container_set_border_width (GTK_CONTAINER (vbox61), 4);

  hbox23 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox23, "hbox23");
  gtk_widget_show (hbox23);
  gtk_box_pack_start (GTK_BOX (vbox61), hbox23, TRUE, TRUE, 0);

  label152 = gtk_label_new ("Resampling step (pix)");
  gtk_widget_set_name (label152, "label152");
  gtk_widget_show (label152);
  gtk_box_pack_start (GTK_BOX (hbox23), label152, FALSE, FALSE, 0);

  spinbutton38_adj = gtk_adjustment_new (2, 0, 100, 1, 10, 10);
  spinbutton38 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton38_adj), 1, 2);
  gtk_widget_set_name (spinbutton38, "spinbutton38");
  gtk_widget_show (spinbutton38);
  gtk_box_pack_start (GTK_BOX (hbox23), spinbutton38, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton38), TRUE);

  checkbutton30 = gtk_check_button_new_with_mnemonic ("Constant abscissa ascendent");
  gtk_widget_set_name (checkbutton30, "checkbutton30");
  gtk_widget_show (checkbutton30);
  gtk_box_pack_start (GTK_BOX (vbox61), checkbutton30, FALSE, FALSE, 0);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox24, "hbox24");
  gtk_widget_show (hbox24);
  gtk_box_pack_start (GTK_BOX (vbox61), hbox24, TRUE, TRUE, 0);

  checkbutton31 = gtk_check_button_new_with_mnemonic ("Autosave temporary path every minutes");
  gtk_widget_set_name (checkbutton31, "checkbutton31");
  gtk_widget_show (checkbutton31);
  gtk_box_pack_start (GTK_BOX (hbox24), checkbutton31, FALSE, FALSE, 0);

  spinbutton39_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton39 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton39_adj), 1, 0);
  gtk_widget_set_name (spinbutton39, "spinbutton39");
  gtk_widget_show (spinbutton39);
  gtk_box_pack_start (GTK_BOX (hbox24), spinbutton39, FALSE, TRUE, 0);

  label153 = gtk_label_new ("Resampling");
  gtk_widget_set_name (label153, "label153");
  gtk_widget_show (label153);
  gtk_frame_set_label_widget (GTK_FRAME (frame48), label153);

  frame49 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame49, "frame49");
  gtk_widget_show (frame49);
  gtk_box_pack_start (GTK_BOX (vbox59), frame49, FALSE, FALSE, 0);

  hbox25 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox25, "hbox25");
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (frame49), hbox25);
  gtk_container_set_border_width (GTK_CONTAINER (hbox25), 4);

  checkbutton32 = gtk_check_button_new_with_mnemonic ("Fitting");
  gtk_widget_set_name (checkbutton32, "checkbutton32");
  gtk_widget_show (checkbutton32);
  gtk_box_pack_start (GTK_BOX (hbox25), checkbutton32, FALSE, FALSE, 0);

  vbox62 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox62, "vbox62");
  gtk_widget_show (vbox62);
  gtk_box_pack_start (GTK_BOX (hbox25), vbox62, FALSE, TRUE, 0);

  radiobutton24 = gtk_radio_button_new_with_mnemonic (NULL, "Polynomial");
  gtk_widget_set_name (radiobutton24, "radiobutton24");
  gtk_widget_show (radiobutton24);
  gtk_box_pack_start (GTK_BOX (vbox62), radiobutton24, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton24), radiobutton24_group);
  radiobutton24_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton24));

  radiobutton25 = gtk_radio_button_new_with_mnemonic (NULL, "Minimum Square");
  gtk_widget_set_name (radiobutton25, "radiobutton25");
  gtk_widget_show (radiobutton25);
  gtk_box_pack_start (GTK_BOX (vbox62), radiobutton25, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton25), radiobutton25_group);
  radiobutton25_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton25));

  hbox26 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox26, "hbox26");
  gtk_widget_show (hbox26);
  gtk_box_pack_start (GTK_BOX (hbox25), hbox26, TRUE, TRUE, 0);

  label154 = gtk_label_new ("Order");
  gtk_widget_set_name (label154, "label154");
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (hbox26), label154, FALSE, FALSE, 0);

  spinbutton40_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton40 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton40_adj), 1, 0);
  gtk_widget_set_name (spinbutton40, "spinbutton40");
  gtk_widget_show (spinbutton40);
  gtk_box_pack_start (GTK_BOX (hbox26), spinbutton40, FALSE, FALSE, 0);

  table10 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table10, "table10");
  gtk_widget_show (table10);
  gtk_box_pack_start (GTK_BOX (hbox25), table10, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table10), 4);

  label155 = gtk_label_new ("SVDFIT");
  gtk_widget_set_name (label155, "label155");
  gtk_widget_show (label155);
  gtk_table_attach (GTK_TABLE (table10), label155, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label155), 0, 0.5);

  label156 = gtk_label_new ("LFIT");
  gtk_widget_set_name (label156, "label156");
  gtk_widget_show (label156);
  gtk_table_attach (GTK_TABLE (table10), label156, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label156), 0, 0.5);

  label157 = gtk_label_new ("points");
  gtk_widget_set_name (label157, "label157");
  gtk_widget_show (label157);
  gtk_table_attach (GTK_TABLE (table10), label157, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label157), 0, 0.5);

  label158 = gtk_label_new ("points");
  gtk_widget_set_name (label158, "label158");
  gtk_widget_show (label158);
  gtk_table_attach (GTK_TABLE (table10), label158, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label158), 0, 0.5);

  entry1 = gtk_entry_new ();
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table10), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry1, 60, -1);

  entry2 = gtk_entry_new ();
  gtk_widget_set_name (entry2, "entry2");
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table10), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry2, 60, -1);

  label159 = gtk_label_new ("Fitting");
  gtk_widget_set_name (label159, "label159");
  gtk_widget_show (label159);
  gtk_frame_set_label_widget (GTK_FRAME (frame49), label159);

  label160 = gtk_label_new ("Adjustment");
  gtk_widget_set_name (label160, "label160");
  gtk_widget_show (label160);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label160);

  dialog_action_area6 = GTK_DIALOG (preferences_dlg)->action_area;
  gtk_widget_set_name (dialog_action_area6, "dialog_action_area6");
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  applybutton1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (applybutton1, "applybutton1");
  gtk_widget_show (applybutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (preferences_dlg), applybutton1, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (applybutton1, GTK_CAN_DEFAULT);

  cancelbutton3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton3, "cancelbutton3");
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (preferences_dlg), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (okbutton3, "okbutton3");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (preferences_dlg), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (preferences_dlg, preferences_dlg, "preferences_dlg");
  GLADE_HOOKUP_OBJECT_NO_REF (preferences_dlg, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (preferences_dlg, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox55, "vbox55");
  GLADE_HOOKUP_OBJECT (preferences_dlg, frame44, "frame44");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox56, "vbox56");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label147, "label147");
  GLADE_HOOKUP_OBJECT (preferences_dlg, frame45, "frame45");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox57, "vbox57");
  GLADE_HOOKUP_OBJECT (preferences_dlg, checkbutton26, "checkbutton26");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label148, "label148");
  GLADE_HOOKUP_OBJECT (preferences_dlg, frame46, "frame46");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox58, "vbox58");
  GLADE_HOOKUP_OBJECT (preferences_dlg, checkbutton27, "checkbutton27");
  GLADE_HOOKUP_OBJECT (preferences_dlg, checkbutton28, "checkbutton28");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label149, "label149");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label150, "label150");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox59, "vbox59");
  GLADE_HOOKUP_OBJECT (preferences_dlg, frame47, "frame47");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox60, "vbox60");
  GLADE_HOOKUP_OBJECT (preferences_dlg, checkbutton29, "checkbutton29");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label151, "label151");
  GLADE_HOOKUP_OBJECT (preferences_dlg, frame48, "frame48");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox61, "vbox61");
  GLADE_HOOKUP_OBJECT (preferences_dlg, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label152, "label152");
  GLADE_HOOKUP_OBJECT (preferences_dlg, spinbutton38, "spinbutton38");
  GLADE_HOOKUP_OBJECT (preferences_dlg, checkbutton30, "checkbutton30");
  GLADE_HOOKUP_OBJECT (preferences_dlg, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (preferences_dlg, checkbutton31, "checkbutton31");
  GLADE_HOOKUP_OBJECT (preferences_dlg, spinbutton39, "spinbutton39");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label153, "label153");
  GLADE_HOOKUP_OBJECT (preferences_dlg, frame49, "frame49");
  GLADE_HOOKUP_OBJECT (preferences_dlg, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (preferences_dlg, checkbutton32, "checkbutton32");
  GLADE_HOOKUP_OBJECT (preferences_dlg, vbox62, "vbox62");
  GLADE_HOOKUP_OBJECT (preferences_dlg, radiobutton24, "radiobutton24");
  GLADE_HOOKUP_OBJECT (preferences_dlg, radiobutton25, "radiobutton25");
  GLADE_HOOKUP_OBJECT (preferences_dlg, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label154, "label154");
  GLADE_HOOKUP_OBJECT (preferences_dlg, spinbutton40, "spinbutton40");
  GLADE_HOOKUP_OBJECT (preferences_dlg, table10, "table10");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label155, "label155");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label156, "label156");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label157, "label157");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label158, "label158");
  GLADE_HOOKUP_OBJECT (preferences_dlg, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (preferences_dlg, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label159, "label159");
  GLADE_HOOKUP_OBJECT (preferences_dlg, label160, "label160");
  GLADE_HOOKUP_OBJECT_NO_REF (preferences_dlg, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (preferences_dlg, applybutton1, "applybutton1");
  GLADE_HOOKUP_OBJECT (preferences_dlg, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (preferences_dlg, okbutton3, "okbutton3");

  return preferences_dlg;
}

