#!/bin/sh

# glibtoolize --force --copy && autoheader && aclocal && autoconf && automake -a -c
# glibtoolize --copy && intltoolize --force && autoheader && aclocal && autoconf && automake -a

intltoolize --force && autoheader && aclocal && autoconf && automake -a

