#!/bin/sh

# glibtoolize --force --copy && autoheader && aclocal && autoconf && automake -a -c
# glibtoolize --copy && intltoolize --force && autoheader && aclocal && autoconf && automake -a

glibtoolize --copy && aclocal &&  autoheader && autoconf && automake -a

