/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_neuronteseo (void);
GtkWidget* create_win_preferences (void);
GtkWidget* create_win_testdevel (void);
GtkWidget* create_window_wait (void);
GtkWidget* create_Teseodialog (void);
