
SHELL = /bin/sh

all:
	g77 1_arm-shift-value-en.f -o 1_arm-shift-value-en
	g77 2_arm-shift-slope-en.f -o 2_arm-shift-slope-en
	g77 3_geometrical-corr-en.f -o 3_geometrical-corr-en
	
clean:
	rm -f 1_arm-shift-value-en  2_arm-shift-slope-en 3_geometrical-corr-en
	
        
